{{- if .Values.imagePullSecrets.create.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.create.name }}
  labels:
    {{- include "grown.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.create.dockerconfigjson | quote }}
{{- end }}
