// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: documents.proto

package documents

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentsService_CreateDocument_FullMethodName         = "/pdf.documents.DocumentsService/CreateDocument"
	DocumentsService_GetDocument_FullMethodName            = "/pdf.documents.DocumentsService/GetDocument"
	DocumentsService_UpdateDocument_FullMethodName         = "/pdf.documents.DocumentsService/UpdateDocument"
	DocumentsService_DeleteDocument_FullMethodName         = "/pdf.documents.DocumentsService/DeleteDocument"
	DocumentsService_ListDocuments_FullMethodName          = "/pdf.documents.DocumentsService/ListDocuments"
	DocumentsService_SendDocument_FullMethodName           = "/pdf.documents.DocumentsService/SendDocument"
	DocumentsService_VoidDocument_FullMethodName           = "/pdf.documents.DocumentsService/VoidDocument"
	DocumentsService_AddSigner_FullMethodName              = "/pdf.documents.DocumentsService/AddSigner"
	DocumentsService_RemoveSigner_FullMethodName           = "/pdf.documents.DocumentsService/RemoveSigner"
	DocumentsService_AddSignatureField_FullMethodName      = "/pdf.documents.DocumentsService/AddSignatureField"
	DocumentsService_UpdateSignatureField_FullMethodName   = "/pdf.documents.DocumentsService/UpdateSignatureField"
	DocumentsService_RemoveSignatureField_FullMethodName   = "/pdf.documents.DocumentsService/RemoveSignatureField"
	DocumentsService_GetCompletedDocument_FullMethodName   = "/pdf.documents.DocumentsService/GetCompletedDocument"
	DocumentsService_GetDocumentSignatures_FullMethodName  = "/pdf.documents.DocumentsService/GetDocumentSignatures"
	DocumentsService_ResendSignerInvitation_FullMethodName = "/pdf.documents.DocumentsService/ResendSignerInvitation"
	DocumentsService_ListDocumentsToSign_FullMethodName    = "/pdf.documents.DocumentsService/ListDocumentsToSign"
	DocumentsService_VerifyDocument_FullMethodName         = "/pdf.documents.DocumentsService/VerifyDocument"
)

// DocumentsServiceClient is the client API for DocumentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Documents service
type DocumentsServiceClient interface {
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*SendDocumentResponse, error)
	VoidDocument(ctx context.Context, in *VoidDocumentRequest, opts ...grpc.CallOption) (*VoidDocumentResponse, error)
	AddSigner(ctx context.Context, in *AddSignerRequest, opts ...grpc.CallOption) (*AddSignerResponse, error)
	RemoveSigner(ctx context.Context, in *RemoveSignerRequest, opts ...grpc.CallOption) (*RemoveSignerResponse, error)
	AddSignatureField(ctx context.Context, in *AddSignatureFieldRequest, opts ...grpc.CallOption) (*AddSignatureFieldResponse, error)
	UpdateSignatureField(ctx context.Context, in *UpdateSignatureFieldRequest, opts ...grpc.CallOption) (*UpdateSignatureFieldResponse, error)
	RemoveSignatureField(ctx context.Context, in *RemoveSignatureFieldRequest, opts ...grpc.CallOption) (*RemoveSignatureFieldResponse, error)
	GetCompletedDocument(ctx context.Context, in *GetCompletedDocumentRequest, opts ...grpc.CallOption) (*GetCompletedDocumentResponse, error)
	GetDocumentSignatures(ctx context.Context, in *GetDocumentSignaturesRequest, opts ...grpc.CallOption) (*GetDocumentSignaturesResponse, error)
	ResendSignerInvitation(ctx context.Context, in *ResendSignerInvitationRequest, opts ...grpc.CallOption) (*ResendSignerInvitationResponse, error)
	ListDocumentsToSign(ctx context.Context, in *ListDocumentsToSignRequest, opts ...grpc.CallOption) (*ListDocumentsToSignResponse, error)
	// Verify document signatures
	VerifyDocument(ctx context.Context, in *VerifyDocumentRequest, opts ...grpc.CallOption) (*VerifyDocumentResponse, error)
}

type documentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentsServiceClient(cc grpc.ClientConnInterface) DocumentsServiceClient {
	return &documentsServiceClient{cc}
}

func (c *documentsServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_CreateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_UpdateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, DocumentsService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*SendDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_SendDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) VoidDocument(ctx context.Context, in *VoidDocumentRequest, opts ...grpc.CallOption) (*VoidDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_VoidDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) AddSigner(ctx context.Context, in *AddSignerRequest, opts ...grpc.CallOption) (*AddSignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSignerResponse)
	err := c.cc.Invoke(ctx, DocumentsService_AddSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) RemoveSigner(ctx context.Context, in *RemoveSignerRequest, opts ...grpc.CallOption) (*RemoveSignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSignerResponse)
	err := c.cc.Invoke(ctx, DocumentsService_RemoveSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) AddSignatureField(ctx context.Context, in *AddSignatureFieldRequest, opts ...grpc.CallOption) (*AddSignatureFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSignatureFieldResponse)
	err := c.cc.Invoke(ctx, DocumentsService_AddSignatureField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) UpdateSignatureField(ctx context.Context, in *UpdateSignatureFieldRequest, opts ...grpc.CallOption) (*UpdateSignatureFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSignatureFieldResponse)
	err := c.cc.Invoke(ctx, DocumentsService_UpdateSignatureField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) RemoveSignatureField(ctx context.Context, in *RemoveSignatureFieldRequest, opts ...grpc.CallOption) (*RemoveSignatureFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSignatureFieldResponse)
	err := c.cc.Invoke(ctx, DocumentsService_RemoveSignatureField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) GetCompletedDocument(ctx context.Context, in *GetCompletedDocumentRequest, opts ...grpc.CallOption) (*GetCompletedDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompletedDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_GetCompletedDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) GetDocumentSignatures(ctx context.Context, in *GetDocumentSignaturesRequest, opts ...grpc.CallOption) (*GetDocumentSignaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentSignaturesResponse)
	err := c.cc.Invoke(ctx, DocumentsService_GetDocumentSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) ResendSignerInvitation(ctx context.Context, in *ResendSignerInvitationRequest, opts ...grpc.CallOption) (*ResendSignerInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendSignerInvitationResponse)
	err := c.cc.Invoke(ctx, DocumentsService_ResendSignerInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) ListDocumentsToSign(ctx context.Context, in *ListDocumentsToSignRequest, opts ...grpc.CallOption) (*ListDocumentsToSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsToSignResponse)
	err := c.cc.Invoke(ctx, DocumentsService_ListDocumentsToSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsServiceClient) VerifyDocument(ctx context.Context, in *VerifyDocumentRequest, opts ...grpc.CallOption) (*VerifyDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentsService_VerifyDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentsServiceServer is the server API for DocumentsService service.
// All implementations must embed UnimplementedDocumentsServiceServer
// for forward compatibility.
//
// Documents service
type DocumentsServiceServer interface {
	CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	SendDocument(context.Context, *SendDocumentRequest) (*SendDocumentResponse, error)
	VoidDocument(context.Context, *VoidDocumentRequest) (*VoidDocumentResponse, error)
	AddSigner(context.Context, *AddSignerRequest) (*AddSignerResponse, error)
	RemoveSigner(context.Context, *RemoveSignerRequest) (*RemoveSignerResponse, error)
	AddSignatureField(context.Context, *AddSignatureFieldRequest) (*AddSignatureFieldResponse, error)
	UpdateSignatureField(context.Context, *UpdateSignatureFieldRequest) (*UpdateSignatureFieldResponse, error)
	RemoveSignatureField(context.Context, *RemoveSignatureFieldRequest) (*RemoveSignatureFieldResponse, error)
	GetCompletedDocument(context.Context, *GetCompletedDocumentRequest) (*GetCompletedDocumentResponse, error)
	GetDocumentSignatures(context.Context, *GetDocumentSignaturesRequest) (*GetDocumentSignaturesResponse, error)
	ResendSignerInvitation(context.Context, *ResendSignerInvitationRequest) (*ResendSignerInvitationResponse, error)
	ListDocumentsToSign(context.Context, *ListDocumentsToSignRequest) (*ListDocumentsToSignResponse, error)
	// Verify document signatures
	VerifyDocument(context.Context, *VerifyDocumentRequest) (*VerifyDocumentResponse, error)
	mustEmbedUnimplementedDocumentsServiceServer()
}

// UnimplementedDocumentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentsServiceServer struct{}

func (UnimplementedDocumentsServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDocumentsServiceServer) SendDocument(context.Context, *SendDocumentRequest) (*SendDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) VoidDocument(context.Context, *VoidDocumentRequest) (*VoidDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoidDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) AddSigner(context.Context, *AddSignerRequest) (*AddSignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSigner not implemented")
}
func (UnimplementedDocumentsServiceServer) RemoveSigner(context.Context, *RemoveSignerRequest) (*RemoveSignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSigner not implemented")
}
func (UnimplementedDocumentsServiceServer) AddSignatureField(context.Context, *AddSignatureFieldRequest) (*AddSignatureFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSignatureField not implemented")
}
func (UnimplementedDocumentsServiceServer) UpdateSignatureField(context.Context, *UpdateSignatureFieldRequest) (*UpdateSignatureFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSignatureField not implemented")
}
func (UnimplementedDocumentsServiceServer) RemoveSignatureField(context.Context, *RemoveSignatureFieldRequest) (*RemoveSignatureFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSignatureField not implemented")
}
func (UnimplementedDocumentsServiceServer) GetCompletedDocument(context.Context, *GetCompletedDocumentRequest) (*GetCompletedDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompletedDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) GetDocumentSignatures(context.Context, *GetDocumentSignaturesRequest) (*GetDocumentSignaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentSignatures not implemented")
}
func (UnimplementedDocumentsServiceServer) ResendSignerInvitation(context.Context, *ResendSignerInvitationRequest) (*ResendSignerInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendSignerInvitation not implemented")
}
func (UnimplementedDocumentsServiceServer) ListDocumentsToSign(context.Context, *ListDocumentsToSignRequest) (*ListDocumentsToSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocumentsToSign not implemented")
}
func (UnimplementedDocumentsServiceServer) VerifyDocument(context.Context, *VerifyDocumentRequest) (*VerifyDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyDocument not implemented")
}
func (UnimplementedDocumentsServiceServer) mustEmbedUnimplementedDocumentsServiceServer() {}
func (UnimplementedDocumentsServiceServer) testEmbeddedByValue()                          {}

// UnsafeDocumentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentsServiceServer will
// result in compilation errors.
type UnsafeDocumentsServiceServer interface {
	mustEmbedUnimplementedDocumentsServiceServer()
}

func RegisterDocumentsServiceServer(s grpc.ServiceRegistrar, srv DocumentsServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentsService_ServiceDesc, srv)
}

func _DocumentsService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_UpdateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_SendDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).SendDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_SendDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).SendDocument(ctx, req.(*SendDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_VoidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).VoidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_VoidDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).VoidDocument(ctx, req.(*VoidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_AddSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).AddSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_AddSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).AddSigner(ctx, req.(*AddSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_RemoveSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).RemoveSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_RemoveSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).RemoveSigner(ctx, req.(*RemoveSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_AddSignatureField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSignatureFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).AddSignatureField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_AddSignatureField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).AddSignatureField(ctx, req.(*AddSignatureFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_UpdateSignatureField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSignatureFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).UpdateSignatureField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_UpdateSignatureField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).UpdateSignatureField(ctx, req.(*UpdateSignatureFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_RemoveSignatureField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSignatureFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).RemoveSignatureField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_RemoveSignatureField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).RemoveSignatureField(ctx, req.(*RemoveSignatureFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_GetCompletedDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompletedDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).GetCompletedDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_GetCompletedDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).GetCompletedDocument(ctx, req.(*GetCompletedDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_GetDocumentSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentSignaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).GetDocumentSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_GetDocumentSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).GetDocumentSignatures(ctx, req.(*GetDocumentSignaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_ResendSignerInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendSignerInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).ResendSignerInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_ResendSignerInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).ResendSignerInvitation(ctx, req.(*ResendSignerInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_ListDocumentsToSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsToSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).ListDocumentsToSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_ListDocumentsToSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).ListDocumentsToSign(ctx, req.(*ListDocumentsToSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentsService_VerifyDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServiceServer).VerifyDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentsService_VerifyDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServiceServer).VerifyDocument(ctx, req.(*VerifyDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentsService_ServiceDesc is the grpc.ServiceDesc for DocumentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdf.documents.DocumentsService",
	HandlerType: (*DocumentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDocument",
			Handler:    _DocumentsService_CreateDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DocumentsService_GetDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _DocumentsService_UpdateDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _DocumentsService_DeleteDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _DocumentsService_ListDocuments_Handler,
		},
		{
			MethodName: "SendDocument",
			Handler:    _DocumentsService_SendDocument_Handler,
		},
		{
			MethodName: "VoidDocument",
			Handler:    _DocumentsService_VoidDocument_Handler,
		},
		{
			MethodName: "AddSigner",
			Handler:    _DocumentsService_AddSigner_Handler,
		},
		{
			MethodName: "RemoveSigner",
			Handler:    _DocumentsService_RemoveSigner_Handler,
		},
		{
			MethodName: "AddSignatureField",
			Handler:    _DocumentsService_AddSignatureField_Handler,
		},
		{
			MethodName: "UpdateSignatureField",
			Handler:    _DocumentsService_UpdateSignatureField_Handler,
		},
		{
			MethodName: "RemoveSignatureField",
			Handler:    _DocumentsService_RemoveSignatureField_Handler,
		},
		{
			MethodName: "GetCompletedDocument",
			Handler:    _DocumentsService_GetCompletedDocument_Handler,
		},
		{
			MethodName: "GetDocumentSignatures",
			Handler:    _DocumentsService_GetDocumentSignatures_Handler,
		},
		{
			MethodName: "ResendSignerInvitation",
			Handler:    _DocumentsService_ResendSignerInvitation_Handler,
		},
		{
			MethodName: "ListDocumentsToSign",
			Handler:    _DocumentsService_ListDocumentsToSign_Handler,
		},
		{
			MethodName: "VerifyDocument",
			Handler:    _DocumentsService_VerifyDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "documents.proto",
}
