// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audit.proto

package audit

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audit action enum
type AuditAction int32

const (
	AuditAction_AUDIT_ACTION_UNSPECIFIED           AuditAction = 0
	AuditAction_AUDIT_ACTION_DOCUMENT_CREATED      AuditAction = 1
	AuditAction_AUDIT_ACTION_DOCUMENT_UPDATED      AuditAction = 2
	AuditAction_AUDIT_ACTION_DOCUMENT_SENT         AuditAction = 3
	AuditAction_AUDIT_ACTION_DOCUMENT_VIEWED       AuditAction = 4
	AuditAction_AUDIT_ACTION_DOCUMENT_COMPLETED    AuditAction = 5
	AuditAction_AUDIT_ACTION_DOCUMENT_DECLINED     AuditAction = 6
	AuditAction_AUDIT_ACTION_DOCUMENT_VOIDED       AuditAction = 7
	AuditAction_AUDIT_ACTION_DOCUMENT_EXPIRED      AuditAction = 8
	AuditAction_AUDIT_ACTION_SIGNER_ADDED          AuditAction = 9
	AuditAction_AUDIT_ACTION_SIGNER_REMOVED        AuditAction = 10
	AuditAction_AUDIT_ACTION_SIGNER_NOTIFIED       AuditAction = 11
	AuditAction_AUDIT_ACTION_SIGNER_REMINDED       AuditAction = 12
	AuditAction_AUDIT_ACTION_FIELD_ADDED           AuditAction = 13
	AuditAction_AUDIT_ACTION_FIELD_UPDATED         AuditAction = 14
	AuditAction_AUDIT_ACTION_FIELD_REMOVED         AuditAction = 15
	AuditAction_AUDIT_ACTION_FIELD_FILLED          AuditAction = 16
	AuditAction_AUDIT_ACTION_SIGNATURE_CAPTURED    AuditAction = 17
	AuditAction_AUDIT_ACTION_SIGNATURE_VALIDATED   AuditAction = 18
	AuditAction_AUDIT_ACTION_CERTIFICATE_ISSUED    AuditAction = 19
	AuditAction_AUDIT_ACTION_CERTIFICATE_VALIDATED AuditAction = 20
)

// Enum value maps for AuditAction.
var (
	AuditAction_name = map[int32]string{
		0:  "AUDIT_ACTION_UNSPECIFIED",
		1:  "AUDIT_ACTION_DOCUMENT_CREATED",
		2:  "AUDIT_ACTION_DOCUMENT_UPDATED",
		3:  "AUDIT_ACTION_DOCUMENT_SENT",
		4:  "AUDIT_ACTION_DOCUMENT_VIEWED",
		5:  "AUDIT_ACTION_DOCUMENT_COMPLETED",
		6:  "AUDIT_ACTION_DOCUMENT_DECLINED",
		7:  "AUDIT_ACTION_DOCUMENT_VOIDED",
		8:  "AUDIT_ACTION_DOCUMENT_EXPIRED",
		9:  "AUDIT_ACTION_SIGNER_ADDED",
		10: "AUDIT_ACTION_SIGNER_REMOVED",
		11: "AUDIT_ACTION_SIGNER_NOTIFIED",
		12: "AUDIT_ACTION_SIGNER_REMINDED",
		13: "AUDIT_ACTION_FIELD_ADDED",
		14: "AUDIT_ACTION_FIELD_UPDATED",
		15: "AUDIT_ACTION_FIELD_REMOVED",
		16: "AUDIT_ACTION_FIELD_FILLED",
		17: "AUDIT_ACTION_SIGNATURE_CAPTURED",
		18: "AUDIT_ACTION_SIGNATURE_VALIDATED",
		19: "AUDIT_ACTION_CERTIFICATE_ISSUED",
		20: "AUDIT_ACTION_CERTIFICATE_VALIDATED",
	}
	AuditAction_value = map[string]int32{
		"AUDIT_ACTION_UNSPECIFIED":           0,
		"AUDIT_ACTION_DOCUMENT_CREATED":      1,
		"AUDIT_ACTION_DOCUMENT_UPDATED":      2,
		"AUDIT_ACTION_DOCUMENT_SENT":         3,
		"AUDIT_ACTION_DOCUMENT_VIEWED":       4,
		"AUDIT_ACTION_DOCUMENT_COMPLETED":    5,
		"AUDIT_ACTION_DOCUMENT_DECLINED":     6,
		"AUDIT_ACTION_DOCUMENT_VOIDED":       7,
		"AUDIT_ACTION_DOCUMENT_EXPIRED":      8,
		"AUDIT_ACTION_SIGNER_ADDED":          9,
		"AUDIT_ACTION_SIGNER_REMOVED":        10,
		"AUDIT_ACTION_SIGNER_NOTIFIED":       11,
		"AUDIT_ACTION_SIGNER_REMINDED":       12,
		"AUDIT_ACTION_FIELD_ADDED":           13,
		"AUDIT_ACTION_FIELD_UPDATED":         14,
		"AUDIT_ACTION_FIELD_REMOVED":         15,
		"AUDIT_ACTION_FIELD_FILLED":          16,
		"AUDIT_ACTION_SIGNATURE_CAPTURED":    17,
		"AUDIT_ACTION_SIGNATURE_VALIDATED":   18,
		"AUDIT_ACTION_CERTIFICATE_ISSUED":    19,
		"AUDIT_ACTION_CERTIFICATE_VALIDATED": 20,
	}
)

func (x AuditAction) Enum() *AuditAction {
	p := new(AuditAction)
	*p = x
	return p
}

func (x AuditAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditAction) Descriptor() protoreflect.EnumDescriptor {
	return file_audit_proto_enumTypes[0].Descriptor()
}

func (AuditAction) Type() protoreflect.EnumType {
	return &file_audit_proto_enumTypes[0]
}

func (x AuditAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditAction.Descriptor instead.
func (AuditAction) EnumDescriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

// Audit entry message
type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SignerId      string                 `protobuf:"bytes,3,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        AuditAction            `protobuf:"varint,5,opt,name=action,proto3,enum=pdf.audit.AuditAction" json:"action,omitempty"`
	ActionDetails string                 `protobuf:"bytes,6,opt,name=action_details,json=actionDetails,proto3" json:"action_details,omitempty"` // JSON string
	IpAddress     string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	GeoLocation   string                 `protobuf:"bytes,9,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AuditEntry) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

func (x *AuditEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEntry) GetAction() AuditAction {
	if x != nil {
		return x.Action
	}
	return AuditAction_AUDIT_ACTION_UNSPECIFIED
}

func (x *AuditEntry) GetActionDetails() string {
	if x != nil {
		return x.ActionDetails
	}
	return ""
}

func (x *AuditEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditEntry) GetGeoLocation() string {
	if x != nil {
		return x.GeoLocation
	}
	return ""
}

func (x *AuditEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Get audit trail
type GetAuditTrailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditTrailRequest) Reset() {
	*x = GetAuditTrailRequest{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditTrailRequest) ProtoMessage() {}

func (x *GetAuditTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditTrailRequest.ProtoReflect.Descriptor instead.
func (*GetAuditTrailRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuditTrailRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetAuditTrailRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAuditTrailRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetAuditTrailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditTrailResponse) Reset() {
	*x = GetAuditTrailResponse{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditTrailResponse) ProtoMessage() {}

func (x *GetAuditTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditTrailResponse.ProtoReflect.Descriptor instead.
func (*GetAuditTrailResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditTrailResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAuditTrailResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetAuditTrailResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\tpdf.audit\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tsigner_id\x18\x03 \x01(\tR\bsignerId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12.\n" +
	"\x06action\x18\x05 \x01(\x0e2\x16.pdf.audit.AuditActionR\x06action\x12%\n" +
	"\x0eaction_details\x18\x06 \x01(\tR\ractionDetails\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x12!\n" +
	"\fgeo_location\x18\t \x01(\tR\vgeoLocation\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x14GetAuditTrailRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x91\x01\n" +
	"\x15GetAuditTrailResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.pdf.audit.AuditEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*\xda\x05\n" +
	"\vAuditAction\x12\x1c\n" +
	"\x18AUDIT_ACTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAUDIT_ACTION_DOCUMENT_CREATED\x10\x01\x12!\n" +
	"\x1dAUDIT_ACTION_DOCUMENT_UPDATED\x10\x02\x12\x1e\n" +
	"\x1aAUDIT_ACTION_DOCUMENT_SENT\x10\x03\x12 \n" +
	"\x1cAUDIT_ACTION_DOCUMENT_VIEWED\x10\x04\x12#\n" +
	"\x1fAUDIT_ACTION_DOCUMENT_COMPLETED\x10\x05\x12\"\n" +
	"\x1eAUDIT_ACTION_DOCUMENT_DECLINED\x10\x06\x12 \n" +
	"\x1cAUDIT_ACTION_DOCUMENT_VOIDED\x10\a\x12!\n" +
	"\x1dAUDIT_ACTION_DOCUMENT_EXPIRED\x10\b\x12\x1d\n" +
	"\x19AUDIT_ACTION_SIGNER_ADDED\x10\t\x12\x1f\n" +
	"\x1bAUDIT_ACTION_SIGNER_REMOVED\x10\n" +
	"\x12 \n" +
	"\x1cAUDIT_ACTION_SIGNER_NOTIFIED\x10\v\x12 \n" +
	"\x1cAUDIT_ACTION_SIGNER_REMINDED\x10\f\x12\x1c\n" +
	"\x18AUDIT_ACTION_FIELD_ADDED\x10\r\x12\x1e\n" +
	"\x1aAUDIT_ACTION_FIELD_UPDATED\x10\x0e\x12\x1e\n" +
	"\x1aAUDIT_ACTION_FIELD_REMOVED\x10\x0f\x12\x1d\n" +
	"\x19AUDIT_ACTION_FIELD_FILLED\x10\x10\x12#\n" +
	"\x1fAUDIT_ACTION_SIGNATURE_CAPTURED\x10\x11\x12$\n" +
	" AUDIT_ACTION_SIGNATURE_VALIDATED\x10\x12\x12#\n" +
	"\x1fAUDIT_ACTION_CERTIFICATE_ISSUED\x10\x13\x12&\n" +
	"\"AUDIT_ACTION_CERTIFICATE_VALIDATED\x10\x142\x8e\x01\n" +
	"\fAuditService\x12~\n" +
	"\rGetAuditTrail\x12\x1f.pdf.audit.GetAuditTrailRequest\x1a .pdf.audit.GetAuditTrailResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/documents/{document_id}/auditB5Z3code.pick.haus/grown/grown/internal/pdf/proto/auditb\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_audit_proto_goTypes = []any{
	(AuditAction)(0),              // 0: pdf.audit.AuditAction
	(*AuditEntry)(nil),            // 1: pdf.audit.AuditEntry
	(*GetAuditTrailRequest)(nil),  // 2: pdf.audit.GetAuditTrailRequest
	(*GetAuditTrailResponse)(nil), // 3: pdf.audit.GetAuditTrailResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_audit_proto_depIdxs = []int32{
	0, // 0: pdf.audit.AuditEntry.action:type_name -> pdf.audit.AuditAction
	4, // 1: pdf.audit.AuditEntry.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: pdf.audit.GetAuditTrailResponse.entries:type_name -> pdf.audit.AuditEntry
	2, // 3: pdf.audit.AuditService.GetAuditTrail:input_type -> pdf.audit.GetAuditTrailRequest
	3, // 4: pdf.audit.AuditService.GetAuditTrail:output_type -> pdf.audit.GetAuditTrailResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		EnumInfos:         file_audit_proto_enumTypes,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
