// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: signing.proto

package signing

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signature field for guest signing
type SigningField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldType     string                 `protobuf:"bytes,2,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	X             float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	Required      bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	Label         string                 `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"`
	IsFilled      bool                   `protobuf:"varint,11,opt,name=is_filled,json=isFilled,proto3" json:"is_filled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningField) Reset() {
	*x = SigningField{}
	mi := &file_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningField) ProtoMessage() {}

func (x *SigningField) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningField.ProtoReflect.Descriptor instead.
func (*SigningField) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{0}
}

func (x *SigningField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SigningField) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *SigningField) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SigningField) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SigningField) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SigningField) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SigningField) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SigningField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *SigningField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SigningField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SigningField) GetIsFilled() bool {
	if x != nil {
		return x.IsFilled
	}
	return false
}

// Signing session for guest signers
type SigningSession struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SignerId            string                 `protobuf:"bytes,1,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	SignerName          string                 `protobuf:"bytes,2,opt,name=signer_name,json=signerName,proto3" json:"signer_name,omitempty"`
	SignerEmail         string                 `protobuf:"bytes,3,opt,name=signer_email,json=signerEmail,proto3" json:"signer_email,omitempty"`
	DocumentId          string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName        string                 `protobuf:"bytes,5,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	DocumentDownloadUrl string                 `protobuf:"bytes,6,opt,name=document_download_url,json=documentDownloadUrl,proto3" json:"document_download_url,omitempty"`
	TotalPages          int32                  `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Fields              []*SigningField        `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	ExpiresAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsSigned            bool                   `protobuf:"varint,10,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	SenderName          string                 `protobuf:"bytes,11,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Message             string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SigningSession) Reset() {
	*x = SigningSession{}
	mi := &file_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningSession) ProtoMessage() {}

func (x *SigningSession) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningSession.ProtoReflect.Descriptor instead.
func (*SigningSession) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{1}
}

func (x *SigningSession) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

func (x *SigningSession) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *SigningSession) GetSignerEmail() string {
	if x != nil {
		return x.SignerEmail
	}
	return ""
}

func (x *SigningSession) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SigningSession) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *SigningSession) GetDocumentDownloadUrl() string {
	if x != nil {
		return x.DocumentDownloadUrl
	}
	return ""
}

func (x *SigningSession) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SigningSession) GetFields() []*SigningField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SigningSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SigningSession) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

func (x *SigningSession) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SigningSession) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get signing session
type GetSigningSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningSessionRequest) Reset() {
	*x = GetSigningSessionRequest{}
	mi := &file_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningSessionRequest) ProtoMessage() {}

func (x *GetSigningSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSigningSessionRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{2}
}

func (x *GetSigningSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSigningSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SigningSession        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningSessionResponse) Reset() {
	*x = GetSigningSessionResponse{}
	mi := &file_signing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningSessionResponse) ProtoMessage() {}

func (x *GetSigningSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSigningSessionResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{3}
}

func (x *GetSigningSessionResponse) GetSession() *SigningSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// Record document view
type RecordViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewRequest) Reset() {
	*x = RecordViewRequest{}
	mi := &file_signing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewRequest) ProtoMessage() {}

func (x *RecordViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewRequest.ProtoReflect.Descriptor instead.
func (*RecordViewRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{4}
}

func (x *RecordViewRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RecordViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewResponse) Reset() {
	*x = RecordViewResponse{}
	mi := &file_signing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewResponse) ProtoMessage() {}

func (x *RecordViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewResponse.ProtoReflect.Descriptor instead.
func (*RecordViewResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{5}
}

func (x *RecordViewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Field value for submission
type FieldValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_signing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{6}
}

func (x *FieldValue) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *FieldValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PDF annotation from frontend editor
type PDFAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // freehand, rectangle, circle, arrow, text, highlight
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	X             float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"` // Normalized 0-1 bounds
	Y             float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	StrokeColor   string                 `protobuf:"bytes,8,opt,name=stroke_color,json=strokeColor,proto3" json:"stroke_color,omitempty"`
	StrokeWidth   float64                `protobuf:"fixed64,9,opt,name=stroke_width,json=strokeWidth,proto3" json:"stroke_width,omitempty"`
	FillColor     string                 `protobuf:"bytes,10,opt,name=fill_color,json=fillColor,proto3" json:"fill_color,omitempty"`
	FillOpacity   float64                `protobuf:"fixed64,11,opt,name=fill_opacity,json=fillOpacity,proto3" json:"fill_opacity,omitempty"`
	Text          string                 `protobuf:"bytes,12,opt,name=text,proto3" json:"text,omitempty"` // For text annotations
	FontSize      float64                `protobuf:"fixed64,13,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	FontColor     string                 `protobuf:"bytes,14,opt,name=font_color,json=fontColor,proto3" json:"font_color,omitempty"`
	Points        []*Point               `protobuf:"bytes,15,rep,name=points,proto3" json:"points,omitempty"` // For freehand paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDFAnnotation) Reset() {
	*x = PDFAnnotation{}
	mi := &file_signing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFAnnotation) ProtoMessage() {}

func (x *PDFAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFAnnotation.ProtoReflect.Descriptor instead.
func (*PDFAnnotation) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{7}
}

func (x *PDFAnnotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PDFAnnotation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PDFAnnotation) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PDFAnnotation) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PDFAnnotation) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PDFAnnotation) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PDFAnnotation) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PDFAnnotation) GetStrokeColor() string {
	if x != nil {
		return x.StrokeColor
	}
	return ""
}

func (x *PDFAnnotation) GetStrokeWidth() float64 {
	if x != nil {
		return x.StrokeWidth
	}
	return 0
}

func (x *PDFAnnotation) GetFillColor() string {
	if x != nil {
		return x.FillColor
	}
	return ""
}

func (x *PDFAnnotation) GetFillOpacity() float64 {
	if x != nil {
		return x.FillOpacity
	}
	return 0
}

func (x *PDFAnnotation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PDFAnnotation) GetFontSize() float64 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *PDFAnnotation) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *PDFAnnotation) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_signing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{8}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Submit signatures
type SubmitSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FieldValues   []*FieldValue          `protobuf:"bytes,2,rep,name=field_values,json=fieldValues,proto3" json:"field_values,omitempty"`
	ConsentGiven  bool                   `protobuf:"varint,3,opt,name=consent_given,json=consentGiven,proto3" json:"consent_given,omitempty"`
	ConsentText   string                 `protobuf:"bytes,4,opt,name=consent_text,json=consentText,proto3" json:"consent_text,omitempty"`
	Annotations   []*PDFAnnotation       `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"` // Optional PDF annotations from editor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSignatureRequest) Reset() {
	*x = SubmitSignatureRequest{}
	mi := &file_signing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSignatureRequest) ProtoMessage() {}

func (x *SubmitSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSignatureRequest.ProtoReflect.Descriptor instead.
func (*SubmitSignatureRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitSignatureRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SubmitSignatureRequest) GetFieldValues() []*FieldValue {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

func (x *SubmitSignatureRequest) GetConsentGiven() bool {
	if x != nil {
		return x.ConsentGiven
	}
	return false
}

func (x *SubmitSignatureRequest) GetConsentText() string {
	if x != nil {
		return x.ConsentText
	}
	return ""
}

func (x *SubmitSignatureRequest) GetAnnotations() []*PDFAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type SubmitSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSignatureResponse) Reset() {
	*x = SubmitSignatureResponse{}
	mi := &file_signing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSignatureResponse) ProtoMessage() {}

func (x *SubmitSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSignatureResponse.ProtoReflect.Descriptor instead.
func (*SubmitSignatureResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitSignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Decline signing
type DeclineSigningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineSigningRequest) Reset() {
	*x = DeclineSigningRequest{}
	mi := &file_signing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineSigningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineSigningRequest) ProtoMessage() {}

func (x *DeclineSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineSigningRequest.ProtoReflect.Descriptor instead.
func (*DeclineSigningRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{11}
}

func (x *DeclineSigningRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeclineSigningRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeclineSigningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineSigningResponse) Reset() {
	*x = DeclineSigningResponse{}
	mi := &file_signing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineSigningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineSigningResponse) ProtoMessage() {}

func (x *DeclineSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineSigningResponse.ProtoReflect.Descriptor instead.
func (*DeclineSigningResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{12}
}

func (x *DeclineSigningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Signing options/configuration
type GetSigningOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningOptionsRequest) Reset() {
	*x = GetSigningOptionsRequest{}
	mi := &file_signing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningOptionsRequest) ProtoMessage() {}

func (x *GetSigningOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSigningOptionsRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{13}
}

func (x *GetSigningOptionsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SigningMethod struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                      // "typed", "drawn", "cac_mtls", "cac_extension"
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                  // Display name
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                    // Description of the method
	Enabled          bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`                                           // Whether this method is enabled
	RequiresRedirect bool                   `protobuf:"varint,5,opt,name=requires_redirect,json=requiresRedirect,proto3" json:"requires_redirect,omitempty"` // True for mTLS (requires redirect to HTTPS endpoint)
	RedirectUrl      string                 `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`                 // URL to redirect to for mTLS signing
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SigningMethod) Reset() {
	*x = SigningMethod{}
	mi := &file_signing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningMethod) ProtoMessage() {}

func (x *SigningMethod) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningMethod.ProtoReflect.Descriptor instead.
func (*SigningMethod) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{14}
}

func (x *SigningMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SigningMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SigningMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SigningMethod) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SigningMethod) GetRequiresRedirect() bool {
	if x != nil {
		return x.RequiresRedirect
	}
	return false
}

func (x *SigningMethod) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetSigningOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*SigningMethod       `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	DefaultMethod string                 `protobuf:"bytes,2,opt,name=default_method,json=defaultMethod,proto3" json:"default_method,omitempty"`
	CacDetected   bool                   `protobuf:"varint,3,opt,name=cac_detected,json=cacDetected,proto3" json:"cac_detected,omitempty"` // True if CAC certificate was detected via mTLS
	CacSubject    string                 `protobuf:"bytes,4,opt,name=cac_subject,json=cacSubject,proto3" json:"cac_subject,omitempty"`     // CAC certificate subject if detected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningOptionsResponse) Reset() {
	*x = GetSigningOptionsResponse{}
	mi := &file_signing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningOptionsResponse) ProtoMessage() {}

func (x *GetSigningOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSigningOptionsResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{15}
}

func (x *GetSigningOptionsResponse) GetMethods() []*SigningMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *GetSigningOptionsResponse) GetDefaultMethod() string {
	if x != nil {
		return x.DefaultMethod
	}
	return ""
}

func (x *GetSigningOptionsResponse) GetCacDetected() bool {
	if x != nil {
		return x.CacDetected
	}
	return false
}

func (x *GetSigningOptionsResponse) GetCacSubject() string {
	if x != nil {
		return x.CacSubject
	}
	return ""
}

// Prepare signature for hash-based signing (browser extension)
type PrepareSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FieldValues   []*FieldValue          `protobuf:"bytes,2,rep,name=field_values,json=fieldValues,proto3" json:"field_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSignatureRequest) Reset() {
	*x = PrepareSignatureRequest{}
	mi := &file_signing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSignatureRequest) ProtoMessage() {}

func (x *PrepareSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSignatureRequest.ProtoReflect.Descriptor instead.
func (*PrepareSignatureRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{16}
}

func (x *PrepareSignatureRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PrepareSignatureRequest) GetFieldValues() []*FieldValue {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

type PrepareSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignatureId   string                 `protobuf:"bytes,1,opt,name=signature_id,json=signatureId,proto3" json:"signature_id,omitempty"`       // ID for this signing operation
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`                                        // Base64-encoded hash to be signed
	HashAlgorithm string                 `protobuf:"bytes,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"` // "SHA256", "SHA384", "SHA512"
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`            // Unix timestamp when this hash expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSignatureResponse) Reset() {
	*x = PrepareSignatureResponse{}
	mi := &file_signing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSignatureResponse) ProtoMessage() {}

func (x *PrepareSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSignatureResponse.ProtoReflect.Descriptor instead.
func (*PrepareSignatureResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{17}
}

func (x *PrepareSignatureResponse) GetSignatureId() string {
	if x != nil {
		return x.SignatureId
	}
	return ""
}

func (x *PrepareSignatureResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PrepareSignatureResponse) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

func (x *PrepareSignatureResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Complete signature with client-provided signature (browser extension)
type CompleteSignatureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SignatureId      string                 `protobuf:"bytes,2,opt,name=signature_id,json=signatureId,proto3" json:"signature_id,omitempty"`                // From PrepareSignatureResponse
	Signature        string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                       // Base64-encoded PKCS#7/CMS signature
	Certificate      string                 `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`                                   // Base64-encoded X.509 certificate
	CertificateChain []string               `protobuf:"bytes,5,rep,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"` // Optional intermediate certificates
	ConsentGiven     bool                   `protobuf:"varint,6,opt,name=consent_given,json=consentGiven,proto3" json:"consent_given,omitempty"`
	ConsentText      string                 `protobuf:"bytes,7,opt,name=consent_text,json=consentText,proto3" json:"consent_text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteSignatureRequest) Reset() {
	*x = CompleteSignatureRequest{}
	mi := &file_signing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignatureRequest) ProtoMessage() {}

func (x *CompleteSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignatureRequest.ProtoReflect.Descriptor instead.
func (*CompleteSignatureRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{18}
}

func (x *CompleteSignatureRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CompleteSignatureRequest) GetSignatureId() string {
	if x != nil {
		return x.SignatureId
	}
	return ""
}

func (x *CompleteSignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CompleteSignatureRequest) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *CompleteSignatureRequest) GetCertificateChain() []string {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *CompleteSignatureRequest) GetConsentGiven() bool {
	if x != nil {
		return x.ConsentGiven
	}
	return false
}

func (x *CompleteSignatureRequest) GetConsentText() string {
	if x != nil {
		return x.ConsentText
	}
	return ""
}

type CompleteSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignatureResponse) Reset() {
	*x = CompleteSignatureResponse{}
	mi := &file_signing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignatureResponse) ProtoMessage() {}

func (x *CompleteSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignatureResponse.ProtoReflect.Descriptor instead.
func (*CompleteSignatureResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteSignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CAC certificate info from mTLS
type CACCertificateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CommonName    string                 `protobuf:"bytes,5,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Organization  string                 `protobuf:"bytes,6,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CACCertificateInfo) Reset() {
	*x = CACCertificateInfo{}
	mi := &file_signing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CACCertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CACCertificateInfo) ProtoMessage() {}

func (x *CACCertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CACCertificateInfo.ProtoReflect.Descriptor instead.
func (*CACCertificateInfo) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{20}
}

func (x *CACCertificateInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CACCertificateInfo) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CACCertificateInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CACCertificateInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CACCertificateInfo) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CACCertificateInfo) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

var File_signing_proto protoreflect.FileDescriptor

const file_signing_proto_rawDesc = "" +
	"\n" +
	"\rsigning.proto\x12\vpdf.signing\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\fSigningField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"field_type\x18\x02 \x01(\tR\tfieldType\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x01R\x06height\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12\x14\n" +
	"\x05label\x18\t \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\tR\x05value\x12\x1b\n" +
	"\tis_filled\x18\v \x01(\bR\bisFilled\"\xd2\x03\n" +
	"\x0eSigningSession\x12\x1b\n" +
	"\tsigner_id\x18\x01 \x01(\tR\bsignerId\x12\x1f\n" +
	"\vsigner_name\x18\x02 \x01(\tR\n" +
	"signerName\x12!\n" +
	"\fsigner_email\x18\x03 \x01(\tR\vsignerEmail\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x05 \x01(\tR\fdocumentName\x122\n" +
	"\x15document_download_url\x18\x06 \x01(\tR\x13documentDownloadUrl\x12\x1f\n" +
	"\vtotal_pages\x18\a \x01(\x05R\n" +
	"totalPages\x121\n" +
	"\x06fields\x18\b \x03(\v2\x19.pdf.signing.SigningFieldR\x06fields\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tis_signed\x18\n" +
	" \x01(\bR\bisSigned\x12\x1f\n" +
	"\vsender_name\x18\v \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\"0\n" +
	"\x18GetSigningSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"R\n" +
	"\x19GetSigningSessionResponse\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.pdf.signing.SigningSessionR\asession\")\n" +
	"\x11RecordViewRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\".\n" +
	"\x12RecordViewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\n" +
	"FieldValue\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa2\x03\n" +
	"\rPDFAnnotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x01R\x06height\x12!\n" +
	"\fstroke_color\x18\b \x01(\tR\vstrokeColor\x12!\n" +
	"\fstroke_width\x18\t \x01(\x01R\vstrokeWidth\x12\x1d\n" +
	"\n" +
	"fill_color\x18\n" +
	" \x01(\tR\tfillColor\x12!\n" +
	"\ffill_opacity\x18\v \x01(\x01R\vfillOpacity\x12\x12\n" +
	"\x04text\x18\f \x01(\tR\x04text\x12\x1b\n" +
	"\tfont_size\x18\r \x01(\x01R\bfontSize\x12\x1d\n" +
	"\n" +
	"font_color\x18\x0e \x01(\tR\tfontColor\x12*\n" +
	"\x06points\x18\x0f \x03(\v2\x12.pdf.signing.PointR\x06points\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xf0\x01\n" +
	"\x16SubmitSignatureRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12:\n" +
	"\ffield_values\x18\x02 \x03(\v2\x17.pdf.signing.FieldValueR\vfieldValues\x12#\n" +
	"\rconsent_given\x18\x03 \x01(\bR\fconsentGiven\x12!\n" +
	"\fconsent_text\x18\x04 \x01(\tR\vconsentText\x12<\n" +
	"\vannotations\x18\x05 \x03(\v2\x1a.pdf.signing.PDFAnnotationR\vannotations\"M\n" +
	"\x17SubmitSignatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x15DeclineSigningRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"2\n" +
	"\x16DeclineSigningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x18GetSigningOptionsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xbf\x01\n" +
	"\rSigningMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12+\n" +
	"\x11requires_redirect\x18\x05 \x01(\bR\x10requiresRedirect\x12!\n" +
	"\fredirect_url\x18\x06 \x01(\tR\vredirectUrl\"\xbc\x01\n" +
	"\x19GetSigningOptionsResponse\x124\n" +
	"\amethods\x18\x01 \x03(\v2\x1a.pdf.signing.SigningMethodR\amethods\x12%\n" +
	"\x0edefault_method\x18\x02 \x01(\tR\rdefaultMethod\x12!\n" +
	"\fcac_detected\x18\x03 \x01(\bR\vcacDetected\x12\x1f\n" +
	"\vcac_subject\x18\x04 \x01(\tR\n" +
	"cacSubject\"k\n" +
	"\x17PrepareSignatureRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12:\n" +
	"\ffield_values\x18\x02 \x03(\v2\x17.pdf.signing.FieldValueR\vfieldValues\"\x97\x01\n" +
	"\x18PrepareSignatureResponse\x12!\n" +
	"\fsignature_id\x18\x01 \x01(\tR\vsignatureId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12%\n" +
	"\x0ehash_algorithm\x18\x03 \x01(\tR\rhashAlgorithm\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x88\x02\n" +
	"\x18CompleteSignatureRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fsignature_id\x18\x02 \x01(\tR\vsignatureId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12 \n" +
	"\vcertificate\x18\x04 \x01(\tR\vcertificate\x12+\n" +
	"\x11certificate_chain\x18\x05 \x03(\tR\x10certificateChain\x12#\n" +
	"\rconsent_given\x18\x06 \x01(\bR\fconsentGiven\x12!\n" +
	"\fconsent_text\x18\a \x01(\tR\vconsentText\"O\n" +
	"\x19CompleteSignatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc6\x01\n" +
	"\x12CACCertificateInfo\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vcommon_name\x18\x05 \x01(\tR\n" +
	"commonName\x12\"\n" +
	"\forganization\x18\x06 \x01(\tR\forganization2\xa2\a\n" +
	"\x0eSigningService\x12}\n" +
	"\x11GetSigningSession\x12%.pdf.signing.GetSigningSessionRequest\x1a&.pdf.signing.GetSigningSessionResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/sign/{token}\x12p\n" +
	"\n" +
	"RecordView\x12\x1e.pdf.signing.RecordViewRequest\x1a\x1f.pdf.signing.RecordViewResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/sign/{token}/view\x12\x81\x01\n" +
	"\x0fSubmitSignature\x12#.pdf.signing.SubmitSignatureRequest\x1a$.pdf.signing.SubmitSignatureResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/sign/{token}/submit\x12\x7f\n" +
	"\x0eDeclineSigning\x12\".pdf.signing.DeclineSigningRequest\x1a#.pdf.signing.DeclineSigningResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/sign/{token}/decline\x12\x85\x01\n" +
	"\x11GetSigningOptions\x12%.pdf.signing.GetSigningOptionsRequest\x1a&.pdf.signing.GetSigningOptionsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/sign/{token}/options\x12\x85\x01\n" +
	"\x10PrepareSignature\x12$.pdf.signing.PrepareSignatureRequest\x1a%.pdf.signing.PrepareSignatureResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/sign/{token}/prepare\x12\x89\x01\n" +
	"\x11CompleteSignature\x12%.pdf.signing.CompleteSignatureRequest\x1a&.pdf.signing.CompleteSignatureResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/sign/{token}/completeB7Z5code.pick.haus/grown/grown/internal/pdf/proto/signingb\x06proto3"

var (
	file_signing_proto_rawDescOnce sync.Once
	file_signing_proto_rawDescData []byte
)

func file_signing_proto_rawDescGZIP() []byte {
	file_signing_proto_rawDescOnce.Do(func() {
		file_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)))
	})
	return file_signing_proto_rawDescData
}

var file_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_signing_proto_goTypes = []any{
	(*SigningField)(nil),              // 0: pdf.signing.SigningField
	(*SigningSession)(nil),            // 1: pdf.signing.SigningSession
	(*GetSigningSessionRequest)(nil),  // 2: pdf.signing.GetSigningSessionRequest
	(*GetSigningSessionResponse)(nil), // 3: pdf.signing.GetSigningSessionResponse
	(*RecordViewRequest)(nil),         // 4: pdf.signing.RecordViewRequest
	(*RecordViewResponse)(nil),        // 5: pdf.signing.RecordViewResponse
	(*FieldValue)(nil),                // 6: pdf.signing.FieldValue
	(*PDFAnnotation)(nil),             // 7: pdf.signing.PDFAnnotation
	(*Point)(nil),                     // 8: pdf.signing.Point
	(*SubmitSignatureRequest)(nil),    // 9: pdf.signing.SubmitSignatureRequest
	(*SubmitSignatureResponse)(nil),   // 10: pdf.signing.SubmitSignatureResponse
	(*DeclineSigningRequest)(nil),     // 11: pdf.signing.DeclineSigningRequest
	(*DeclineSigningResponse)(nil),    // 12: pdf.signing.DeclineSigningResponse
	(*GetSigningOptionsRequest)(nil),  // 13: pdf.signing.GetSigningOptionsRequest
	(*SigningMethod)(nil),             // 14: pdf.signing.SigningMethod
	(*GetSigningOptionsResponse)(nil), // 15: pdf.signing.GetSigningOptionsResponse
	(*PrepareSignatureRequest)(nil),   // 16: pdf.signing.PrepareSignatureRequest
	(*PrepareSignatureResponse)(nil),  // 17: pdf.signing.PrepareSignatureResponse
	(*CompleteSignatureRequest)(nil),  // 18: pdf.signing.CompleteSignatureRequest
	(*CompleteSignatureResponse)(nil), // 19: pdf.signing.CompleteSignatureResponse
	(*CACCertificateInfo)(nil),        // 20: pdf.signing.CACCertificateInfo
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_signing_proto_depIdxs = []int32{
	0,  // 0: pdf.signing.SigningSession.fields:type_name -> pdf.signing.SigningField
	21, // 1: pdf.signing.SigningSession.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: pdf.signing.GetSigningSessionResponse.session:type_name -> pdf.signing.SigningSession
	8,  // 3: pdf.signing.PDFAnnotation.points:type_name -> pdf.signing.Point
	6,  // 4: pdf.signing.SubmitSignatureRequest.field_values:type_name -> pdf.signing.FieldValue
	7,  // 5: pdf.signing.SubmitSignatureRequest.annotations:type_name -> pdf.signing.PDFAnnotation
	14, // 6: pdf.signing.GetSigningOptionsResponse.methods:type_name -> pdf.signing.SigningMethod
	6,  // 7: pdf.signing.PrepareSignatureRequest.field_values:type_name -> pdf.signing.FieldValue
	2,  // 8: pdf.signing.SigningService.GetSigningSession:input_type -> pdf.signing.GetSigningSessionRequest
	4,  // 9: pdf.signing.SigningService.RecordView:input_type -> pdf.signing.RecordViewRequest
	9,  // 10: pdf.signing.SigningService.SubmitSignature:input_type -> pdf.signing.SubmitSignatureRequest
	11, // 11: pdf.signing.SigningService.DeclineSigning:input_type -> pdf.signing.DeclineSigningRequest
	13, // 12: pdf.signing.SigningService.GetSigningOptions:input_type -> pdf.signing.GetSigningOptionsRequest
	16, // 13: pdf.signing.SigningService.PrepareSignature:input_type -> pdf.signing.PrepareSignatureRequest
	18, // 14: pdf.signing.SigningService.CompleteSignature:input_type -> pdf.signing.CompleteSignatureRequest
	3,  // 15: pdf.signing.SigningService.GetSigningSession:output_type -> pdf.signing.GetSigningSessionResponse
	5,  // 16: pdf.signing.SigningService.RecordView:output_type -> pdf.signing.RecordViewResponse
	10, // 17: pdf.signing.SigningService.SubmitSignature:output_type -> pdf.signing.SubmitSignatureResponse
	12, // 18: pdf.signing.SigningService.DeclineSigning:output_type -> pdf.signing.DeclineSigningResponse
	15, // 19: pdf.signing.SigningService.GetSigningOptions:output_type -> pdf.signing.GetSigningOptionsResponse
	17, // 20: pdf.signing.SigningService.PrepareSignature:output_type -> pdf.signing.PrepareSignatureResponse
	19, // 21: pdf.signing.SigningService.CompleteSignature:output_type -> pdf.signing.CompleteSignatureResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_signing_proto_init() }
func file_signing_proto_init() {
	if File_signing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signing_proto_goTypes,
		DependencyIndexes: file_signing_proto_depIdxs,
		MessageInfos:      file_signing_proto_msgTypes,
	}.Build()
	File_signing_proto = out.File
	file_signing_proto_goTypes = nil
	file_signing_proto_depIdxs = nil
}
