// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: signing.proto

package signing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SigningService_GetSigningSession_FullMethodName = "/pdf.signing.SigningService/GetSigningSession"
	SigningService_RecordView_FullMethodName        = "/pdf.signing.SigningService/RecordView"
	SigningService_SubmitSignature_FullMethodName   = "/pdf.signing.SigningService/SubmitSignature"
	SigningService_DeclineSigning_FullMethodName    = "/pdf.signing.SigningService/DeclineSigning"
	SigningService_GetSigningOptions_FullMethodName = "/pdf.signing.SigningService/GetSigningOptions"
	SigningService_PrepareSignature_FullMethodName  = "/pdf.signing.SigningService/PrepareSignature"
	SigningService_CompleteSignature_FullMethodName = "/pdf.signing.SigningService/CompleteSignature"
)

// SigningServiceClient is the client API for SigningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Signing service (guest endpoints)
type SigningServiceClient interface {
	// Get signing session details (no auth required, token-based)
	GetSigningSession(ctx context.Context, in *GetSigningSessionRequest, opts ...grpc.CallOption) (*GetSigningSessionResponse, error)
	// Record that document was viewed
	RecordView(ctx context.Context, in *RecordViewRequest, opts ...grpc.CallOption) (*RecordViewResponse, error)
	// Submit signatures
	SubmitSignature(ctx context.Context, in *SubmitSignatureRequest, opts ...grpc.CallOption) (*SubmitSignatureResponse, error)
	// Decline to sign
	DeclineSigning(ctx context.Context, in *DeclineSigningRequest, opts ...grpc.CallOption) (*DeclineSigningResponse, error)
	// Get available signing methods (CAC, typed, etc.)
	GetSigningOptions(ctx context.Context, in *GetSigningOptionsRequest, opts ...grpc.CallOption) (*GetSigningOptionsResponse, error)
	// Prepare signature for hash-based signing (browser extension)
	PrepareSignature(ctx context.Context, in *PrepareSignatureRequest, opts ...grpc.CallOption) (*PrepareSignatureResponse, error)
	// Complete signature with client-provided signature (browser extension)
	CompleteSignature(ctx context.Context, in *CompleteSignatureRequest, opts ...grpc.CallOption) (*CompleteSignatureResponse, error)
}

type signingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningServiceClient(cc grpc.ClientConnInterface) SigningServiceClient {
	return &signingServiceClient{cc}
}

func (c *signingServiceClient) GetSigningSession(ctx context.Context, in *GetSigningSessionRequest, opts ...grpc.CallOption) (*GetSigningSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningSessionResponse)
	err := c.cc.Invoke(ctx, SigningService_GetSigningSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) RecordView(ctx context.Context, in *RecordViewRequest, opts ...grpc.CallOption) (*RecordViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordViewResponse)
	err := c.cc.Invoke(ctx, SigningService_RecordView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) SubmitSignature(ctx context.Context, in *SubmitSignatureRequest, opts ...grpc.CallOption) (*SubmitSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSignatureResponse)
	err := c.cc.Invoke(ctx, SigningService_SubmitSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) DeclineSigning(ctx context.Context, in *DeclineSigningRequest, opts ...grpc.CallOption) (*DeclineSigningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineSigningResponse)
	err := c.cc.Invoke(ctx, SigningService_DeclineSigning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) GetSigningOptions(ctx context.Context, in *GetSigningOptionsRequest, opts ...grpc.CallOption) (*GetSigningOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningOptionsResponse)
	err := c.cc.Invoke(ctx, SigningService_GetSigningOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) PrepareSignature(ctx context.Context, in *PrepareSignatureRequest, opts ...grpc.CallOption) (*PrepareSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSignatureResponse)
	err := c.cc.Invoke(ctx, SigningService_PrepareSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) CompleteSignature(ctx context.Context, in *CompleteSignatureRequest, opts ...grpc.CallOption) (*CompleteSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSignatureResponse)
	err := c.cc.Invoke(ctx, SigningService_CompleteSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningServiceServer is the server API for SigningService service.
// All implementations must embed UnimplementedSigningServiceServer
// for forward compatibility.
//
// Signing service (guest endpoints)
type SigningServiceServer interface {
	// Get signing session details (no auth required, token-based)
	GetSigningSession(context.Context, *GetSigningSessionRequest) (*GetSigningSessionResponse, error)
	// Record that document was viewed
	RecordView(context.Context, *RecordViewRequest) (*RecordViewResponse, error)
	// Submit signatures
	SubmitSignature(context.Context, *SubmitSignatureRequest) (*SubmitSignatureResponse, error)
	// Decline to sign
	DeclineSigning(context.Context, *DeclineSigningRequest) (*DeclineSigningResponse, error)
	// Get available signing methods (CAC, typed, etc.)
	GetSigningOptions(context.Context, *GetSigningOptionsRequest) (*GetSigningOptionsResponse, error)
	// Prepare signature for hash-based signing (browser extension)
	PrepareSignature(context.Context, *PrepareSignatureRequest) (*PrepareSignatureResponse, error)
	// Complete signature with client-provided signature (browser extension)
	CompleteSignature(context.Context, *CompleteSignatureRequest) (*CompleteSignatureResponse, error)
	mustEmbedUnimplementedSigningServiceServer()
}

// UnimplementedSigningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigningServiceServer struct{}

func (UnimplementedSigningServiceServer) GetSigningSession(context.Context, *GetSigningSessionRequest) (*GetSigningSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSigningSession not implemented")
}
func (UnimplementedSigningServiceServer) RecordView(context.Context, *RecordViewRequest) (*RecordViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordView not implemented")
}
func (UnimplementedSigningServiceServer) SubmitSignature(context.Context, *SubmitSignatureRequest) (*SubmitSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSignature not implemented")
}
func (UnimplementedSigningServiceServer) DeclineSigning(context.Context, *DeclineSigningRequest) (*DeclineSigningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclineSigning not implemented")
}
func (UnimplementedSigningServiceServer) GetSigningOptions(context.Context, *GetSigningOptionsRequest) (*GetSigningOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSigningOptions not implemented")
}
func (UnimplementedSigningServiceServer) PrepareSignature(context.Context, *PrepareSignatureRequest) (*PrepareSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSignature not implemented")
}
func (UnimplementedSigningServiceServer) CompleteSignature(context.Context, *CompleteSignatureRequest) (*CompleteSignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteSignature not implemented")
}
func (UnimplementedSigningServiceServer) mustEmbedUnimplementedSigningServiceServer() {}
func (UnimplementedSigningServiceServer) testEmbeddedByValue()                        {}

// UnsafeSigningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningServiceServer will
// result in compilation errors.
type UnsafeSigningServiceServer interface {
	mustEmbedUnimplementedSigningServiceServer()
}

func RegisterSigningServiceServer(s grpc.ServiceRegistrar, srv SigningServiceServer) {
	// If the following call panics, it indicates UnimplementedSigningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SigningService_ServiceDesc, srv)
}

func _SigningService_GetSigningSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).GetSigningSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_GetSigningSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).GetSigningSession(ctx, req.(*GetSigningSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_RecordView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).RecordView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_RecordView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).RecordView(ctx, req.(*RecordViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_SubmitSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).SubmitSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_SubmitSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).SubmitSignature(ctx, req.(*SubmitSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_DeclineSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).DeclineSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_DeclineSigning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).DeclineSigning(ctx, req.(*DeclineSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_GetSigningOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).GetSigningOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_GetSigningOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).GetSigningOptions(ctx, req.(*GetSigningOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_PrepareSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).PrepareSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_PrepareSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).PrepareSignature(ctx, req.(*PrepareSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_CompleteSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).CompleteSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_CompleteSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).CompleteSignature(ctx, req.(*CompleteSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningService_ServiceDesc is the grpc.ServiceDesc for SigningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdf.signing.SigningService",
	HandlerType: (*SigningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSigningSession",
			Handler:    _SigningService_GetSigningSession_Handler,
		},
		{
			MethodName: "RecordView",
			Handler:    _SigningService_RecordView_Handler,
		},
		{
			MethodName: "SubmitSignature",
			Handler:    _SigningService_SubmitSignature_Handler,
		},
		{
			MethodName: "DeclineSigning",
			Handler:    _SigningService_DeclineSigning_Handler,
		},
		{
			MethodName: "GetSigningOptions",
			Handler:    _SigningService_GetSigningOptions_Handler,
		},
		{
			MethodName: "PrepareSignature",
			Handler:    _SigningService_PrepareSignature_Handler,
		},
		{
			MethodName: "CompleteSignature",
			Handler:    _SigningService_CompleteSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signing.proto",
}
