// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_trail.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT COUNT(*) FROM audit_trail WHERE document_id = $1
`

func (q *Queries) CountAuditEntries(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_trail (
    id, document_id, signer_id, user_id, action, action_details,
    ip_address, user_agent, geo_location
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, document_id, signer_id, user_id, action, action_details, ip_address, user_agent, geo_location, created_at
`

type CreateAuditEntryParams struct {
	ID            string      `json:"id"`
	DocumentID    string      `json:"document_id"`
	SignerID      pgtype.Text `json:"signer_id"`
	UserID        pgtype.Text `json:"user_id"`
	Action        AuditAction `json:"action"`
	ActionDetails []byte      `json:"action_details"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	GeoLocation   pgtype.Text `json:"geo_location"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditTrail, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ID,
		arg.DocumentID,
		arg.SignerID,
		arg.UserID,
		arg.Action,
		arg.ActionDetails,
		arg.IpAddress,
		arg.UserAgent,
		arg.GeoLocation,
	)
	var i AuditTrail
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.UserID,
		&i.Action,
		&i.ActionDetails,
		&i.IpAddress,
		&i.UserAgent,
		&i.GeoLocation,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditEntriesByAction = `-- name: GetAuditEntriesByAction :many
SELECT id, document_id, signer_id, user_id, action, action_details, ip_address, user_agent, geo_location, created_at FROM audit_trail
WHERE document_id = $1 AND action = $2
ORDER BY created_at DESC
`

type GetAuditEntriesByActionParams struct {
	DocumentID string      `json:"document_id"`
	Action     AuditAction `json:"action"`
}

func (q *Queries) GetAuditEntriesByAction(ctx context.Context, arg GetAuditEntriesByActionParams) ([]AuditTrail, error) {
	rows, err := q.db.Query(ctx, getAuditEntriesByAction, arg.DocumentID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditTrail{}
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.UserID,
			&i.Action,
			&i.ActionDetails,
			&i.IpAddress,
			&i.UserAgent,
			&i.GeoLocation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditEntriesBySigner = `-- name: GetAuditEntriesBySigner :many
SELECT id, document_id, signer_id, user_id, action, action_details, ip_address, user_agent, geo_location, created_at FROM audit_trail
WHERE signer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuditEntriesBySigner(ctx context.Context, signerID pgtype.Text) ([]AuditTrail, error) {
	rows, err := q.db.Query(ctx, getAuditEntriesBySigner, signerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditTrail{}
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.UserID,
			&i.Action,
			&i.ActionDetails,
			&i.IpAddress,
			&i.UserAgent,
			&i.GeoLocation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditTrail = `-- name: GetAuditTrail :many
SELECT id, document_id, signer_id, user_id, action, action_details, ip_address, user_agent, geo_location, created_at FROM audit_trail
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditTrailParams struct {
	DocumentID string `json:"document_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetAuditTrail(ctx context.Context, arg GetAuditTrailParams) ([]AuditTrail, error) {
	rows, err := q.db.Query(ctx, getAuditTrail, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditTrail{}
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.UserID,
			&i.Action,
			&i.ActionDetails,
			&i.IpAddress,
			&i.UserAgent,
			&i.GeoLocation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
