// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSigningCertificate = `-- name: CreateSigningCertificate :one
INSERT INTO signing_certificates (
    id, organization_id, user_id, certificate_type, status,
    certificate_pem, private_key_encrypted, key_encryption_key_id,
    serial_number, issuer_dn, subject_dn, valid_from, valid_to,
    ca_name, ca_certificate_chain
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason
`

type CreateSigningCertificateParams struct {
	ID                  string             `json:"id"`
	OrganizationID      string             `json:"organization_id"`
	UserID              pgtype.Text        `json:"user_id"`
	CertificateType     CertificateType    `json:"certificate_type"`
	Status              CertificateStatus  `json:"status"`
	CertificatePem      string             `json:"certificate_pem"`
	PrivateKeyEncrypted []byte             `json:"private_key_encrypted"`
	KeyEncryptionKeyID  string             `json:"key_encryption_key_id"`
	SerialNumber        string             `json:"serial_number"`
	IssuerDn            string             `json:"issuer_dn"`
	SubjectDn           string             `json:"subject_dn"`
	ValidFrom           pgtype.Timestamptz `json:"valid_from"`
	ValidTo             pgtype.Timestamptz `json:"valid_to"`
	CaName              string             `json:"ca_name"`
	CaCertificateChain  string             `json:"ca_certificate_chain"`
}

func (q *Queries) CreateSigningCertificate(ctx context.Context, arg CreateSigningCertificateParams) (SigningCertificate, error) {
	row := q.db.QueryRow(ctx, createSigningCertificate,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.CertificateType,
		arg.Status,
		arg.CertificatePem,
		arg.PrivateKeyEncrypted,
		arg.KeyEncryptionKeyID,
		arg.SerialNumber,
		arg.IssuerDn,
		arg.SubjectDn,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CaName,
		arg.CaCertificateChain,
	)
	var i SigningCertificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CertificateType,
		&i.Status,
		&i.CertificatePem,
		&i.PrivateKeyEncrypted,
		&i.KeyEncryptionKeyID,
		&i.SerialNumber,
		&i.IssuerDn,
		&i.SubjectDn,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CaName,
		&i.CaCertificateChain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getActiveCertificateByOrg = `-- name: GetActiveCertificateByOrg :one
SELECT id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason FROM signing_certificates
WHERE organization_id = $1 AND user_id IS NULL AND status = 'active' AND valid_to > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCertificateByOrg(ctx context.Context, organizationID string) (SigningCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveCertificateByOrg, organizationID)
	var i SigningCertificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CertificateType,
		&i.Status,
		&i.CertificatePem,
		&i.PrivateKeyEncrypted,
		&i.KeyEncryptionKeyID,
		&i.SerialNumber,
		&i.IssuerDn,
		&i.SubjectDn,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CaName,
		&i.CaCertificateChain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getActiveCertificateByUser = `-- name: GetActiveCertificateByUser :one
SELECT id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason FROM signing_certificates
WHERE user_id = $1 AND status = 'active' AND valid_to > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCertificateByUser(ctx context.Context, userID pgtype.Text) (SigningCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveCertificateByUser, userID)
	var i SigningCertificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CertificateType,
		&i.Status,
		&i.CertificatePem,
		&i.PrivateKeyEncrypted,
		&i.KeyEncryptionKeyID,
		&i.SerialNumber,
		&i.IssuerDn,
		&i.SubjectDn,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CaName,
		&i.CaCertificateChain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getExpiredCertificates = `-- name: GetExpiredCertificates :many
SELECT id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason FROM signing_certificates
WHERE status = 'active' AND valid_to < NOW()
`

func (q *Queries) GetExpiredCertificates(ctx context.Context) ([]SigningCertificate, error) {
	rows, err := q.db.Query(ctx, getExpiredCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningCertificate{}
	for rows.Next() {
		var i SigningCertificate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.CertificateType,
			&i.Status,
			&i.CertificatePem,
			&i.PrivateKeyEncrypted,
			&i.KeyEncryptionKeyID,
			&i.SerialNumber,
			&i.IssuerDn,
			&i.SubjectDn,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CaName,
			&i.CaCertificateChain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.RevocationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigningCertificate = `-- name: GetSigningCertificate :one
SELECT id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason FROM signing_certificates WHERE id = $1
`

func (q *Queries) GetSigningCertificate(ctx context.Context, id string) (SigningCertificate, error) {
	row := q.db.QueryRow(ctx, getSigningCertificate, id)
	var i SigningCertificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CertificateType,
		&i.Status,
		&i.CertificatePem,
		&i.PrivateKeyEncrypted,
		&i.KeyEncryptionKeyID,
		&i.SerialNumber,
		&i.IssuerDn,
		&i.SubjectDn,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CaName,
		&i.CaCertificateChain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const listCertificatesByOrg = `-- name: ListCertificatesByOrg :many
SELECT id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason FROM signing_certificates
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCertificatesByOrg(ctx context.Context, organizationID string) ([]SigningCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningCertificate{}
	for rows.Next() {
		var i SigningCertificate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.CertificateType,
			&i.Status,
			&i.CertificatePem,
			&i.PrivateKeyEncrypted,
			&i.KeyEncryptionKeyID,
			&i.SerialNumber,
			&i.IssuerDn,
			&i.SubjectDn,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CaName,
			&i.CaCertificateChain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.RevocationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE signing_certificates
SET status = 'revoked', revoked_at = NOW(), revocation_reason = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, certificate_type, status, certificate_pem, private_key_encrypted, key_encryption_key_id, serial_number, issuer_dn, subject_dn, valid_from, valid_to, ca_name, ca_certificate_chain, created_at, updated_at, revoked_at, revocation_reason
`

type RevokeCertificateParams struct {
	ID               string      `json:"id"`
	RevocationReason pgtype.Text `json:"revocation_reason"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (SigningCertificate, error) {
	row := q.db.QueryRow(ctx, revokeCertificate, arg.ID, arg.RevocationReason)
	var i SigningCertificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CertificateType,
		&i.Status,
		&i.CertificatePem,
		&i.PrivateKeyEncrypted,
		&i.KeyEncryptionKeyID,
		&i.SerialNumber,
		&i.IssuerDn,
		&i.SubjectDn,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CaName,
		&i.CaCertificateChain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}
