// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllDocuments = `-- name: CountAllDocuments :one
SELECT COUNT(*) FROM documents
`

func (q *Queries) CountAllDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByOrg = `-- name: CountDocumentsByOrg :one
SELECT COUNT(*) FROM documents WHERE organization_id = $1
`

func (q *Queries) CountDocumentsByOrg(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByOrgAndStatus = `-- name: CountDocumentsByOrgAndStatus :one
SELECT COUNT(*) FROM documents WHERE organization_id = $1 AND status = $2
`

type CountDocumentsByOrgAndStatusParams struct {
	OrganizationID string         `json:"organization_id"`
	Status         DocumentStatus `json:"status"`
}

func (q *Queries) CountDocumentsByOrgAndStatus(ctx context.Context, arg CountDocumentsByOrgAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByOrgAndStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsForUser = `-- name: CountDocumentsForUser :one
SELECT count(*)::int FROM documents WHERE lower(created_by) = lower($1)
`

func (q *Queries) CountDocumentsForUser(ctx context.Context, lower string) (int32, error) {
	row := q.db.QueryRow(ctx, countDocumentsForUser, lower)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, organization_id, name, description, status, storage_key,
    total_pages, file_size_bytes, signing_order, expires_at,
    reminder_frequency_days, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type CreateDocumentParams struct {
	ID                    string             `json:"id"`
	OrganizationID        string             `json:"organization_id"`
	Name                  string             `json:"name"`
	Description           pgtype.Text        `json:"description"`
	Status                DocumentStatus     `json:"status"`
	StorageKey            string             `json:"storage_key"`
	TotalPages            int32              `json:"total_pages"`
	FileSizeBytes         pgtype.Int8        `json:"file_size_bytes"`
	SigningOrder          bool               `json:"signing_order"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ReminderFrequencyDays pgtype.Int4        `json:"reminder_frequency_days"`
	CreatedBy             string             `json:"created_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StorageKey,
		arg.TotalPages,
		arg.FileSizeBytes,
		arg.SigningOrder,
		arg.ExpiresAt,
		arg.ReminderFrequencyDays,
		arg.CreatedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const getDocumentAnnotations = `-- name: GetDocumentAnnotations :one
SELECT annotations FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentAnnotations(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDocumentAnnotations, id)
	var annotations []byte
	err := row.Scan(&annotations)
	return annotations, err
}

const getDocumentByOrg = `-- name: GetDocumentByOrg :one
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents WHERE id = $1 AND organization_id = $2
`

type GetDocumentByOrgParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetDocumentByOrg(ctx context.Context, arg GetDocumentByOrgParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByOrg, arg.ID, arg.OrganizationID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const getExpiredDocuments = `-- name: GetExpiredDocuments :many
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents
WHERE status IN ('pending', 'in_progress')
AND expires_at IS NOT NULL
AND expires_at < NOW()
`

func (q *Queries) GetExpiredDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, getExpiredDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageKey,
			&i.SignedStorageKey,
			&i.TotalPages,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.SigningOrder,
			&i.ExpiresAt,
			&i.ReminderFrequencyDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listAllDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageKey,
			&i.SignedStorageKey,
			&i.TotalPages,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.SigningOrder,
			&i.ExpiresAt,
			&i.ReminderFrequencyDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByOrg = `-- name: ListDocumentsByOrg :many
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByOrgParams struct {
	OrganizationID string `json:"organization_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByOrg(ctx context.Context, arg ListDocumentsByOrgParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageKey,
			&i.SignedStorageKey,
			&i.TotalPages,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.SigningOrder,
			&i.ExpiresAt,
			&i.ReminderFrequencyDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByOrgAndStatus = `-- name: ListDocumentsByOrgAndStatus :many
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents
WHERE organization_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDocumentsByOrgAndStatusParams struct {
	OrganizationID string         `json:"organization_id"`
	Status         DocumentStatus `json:"status"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

func (q *Queries) ListDocumentsByOrgAndStatus(ctx context.Context, arg ListDocumentsByOrgAndStatusParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOrgAndStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageKey,
			&i.SignedStorageKey,
			&i.TotalPages,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.SigningOrder,
			&i.ExpiresAt,
			&i.ReminderFrequencyDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForUser = `-- name: ListDocumentsForUser :many
SELECT id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations FROM documents
WHERE lower(created_by) = lower($1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsForUserParams struct {
	Lower  string `json:"lower"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDocumentsForUser(ctx context.Context, arg ListDocumentsForUserParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsForUser, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageKey,
			&i.SignedStorageKey,
			&i.TotalPages,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.SigningOrder,
			&i.ExpiresAt,
			&i.ReminderFrequencyDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET name = $2, description = $3, signing_order = $4, expires_at = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type UpdateDocumentParams struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	SigningOrder bool               `json:"signing_order"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SigningOrder,
		arg.ExpiresAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const updateDocumentAnnotations = `-- name: UpdateDocumentAnnotations :exec
UPDATE documents SET annotations = $2, updated_at = now() WHERE id = $1
`

type UpdateDocumentAnnotationsParams struct {
	ID          string `json:"id"`
	Annotations []byte `json:"annotations"`
}

func (q *Queries) UpdateDocumentAnnotations(ctx context.Context, arg UpdateDocumentAnnotationsParams) error {
	_, err := q.db.Exec(ctx, updateDocumentAnnotations, arg.ID, arg.Annotations)
	return err
}

const updateDocumentCompleted = `-- name: UpdateDocumentCompleted :one
UPDATE documents
SET status = 'completed', signed_storage_key = $2, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type UpdateDocumentCompletedParams struct {
	ID               string      `json:"id"`
	SignedStorageKey pgtype.Text `json:"signed_storage_key"`
}

func (q *Queries) UpdateDocumentCompleted(ctx context.Context, arg UpdateDocumentCompletedParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentCompleted, arg.ID, arg.SignedStorageKey)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const updateDocumentPageCount = `-- name: UpdateDocumentPageCount :one
UPDATE documents
SET total_pages = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type UpdateDocumentPageCountParams struct {
	ID         string `json:"id"`
	TotalPages int32  `json:"total_pages"`
}

func (q *Queries) UpdateDocumentPageCount(ctx context.Context, arg UpdateDocumentPageCountParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentPageCount, arg.ID, arg.TotalPages)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const updateDocumentSignedKey = `-- name: UpdateDocumentSignedKey :one
UPDATE documents
SET signed_storage_key = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type UpdateDocumentSignedKeyParams struct {
	ID               string      `json:"id"`
	SignedStorageKey pgtype.Text `json:"signed_storage_key"`
}

func (q *Queries) UpdateDocumentSignedKey(ctx context.Context, arg UpdateDocumentSignedKeyParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentSignedKey, arg.ID, arg.SignedStorageKey)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, status, storage_key, signed_storage_key, total_pages, file_size_bytes, mime_type, signing_order, expires_at, reminder_frequency_days, created_by, created_at, updated_at, completed_at, annotations
`

type UpdateDocumentStatusParams struct {
	ID     string         `json:"id"`
	Status DocumentStatus `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageKey,
		&i.SignedStorageKey,
		&i.TotalPages,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.SigningOrder,
		&i.ExpiresAt,
		&i.ReminderFrequencyDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Annotations,
	)
	return i, err
}
