// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAction string

const (
	AuditActionDocumentCreated      AuditAction = "document_created"
	AuditActionDocumentUpdated      AuditAction = "document_updated"
	AuditActionDocumentSent         AuditAction = "document_sent"
	AuditActionDocumentViewed       AuditAction = "document_viewed"
	AuditActionDocumentCompleted    AuditAction = "document_completed"
	AuditActionDocumentDeclined     AuditAction = "document_declined"
	AuditActionDocumentVoided       AuditAction = "document_voided"
	AuditActionDocumentExpired      AuditAction = "document_expired"
	AuditActionSignerAdded          AuditAction = "signer_added"
	AuditActionSignerRemoved        AuditAction = "signer_removed"
	AuditActionSignerNotified       AuditAction = "signer_notified"
	AuditActionSignerReminded       AuditAction = "signer_reminded"
	AuditActionFieldAdded           AuditAction = "field_added"
	AuditActionFieldUpdated         AuditAction = "field_updated"
	AuditActionFieldRemoved         AuditAction = "field_removed"
	AuditActionFieldFilled          AuditAction = "field_filled"
	AuditActionSignatureCaptured    AuditAction = "signature_captured"
	AuditActionSignatureValidated   AuditAction = "signature_validated"
	AuditActionCertificateIssued    AuditAction = "certificate_issued"
	AuditActionCertificateValidated AuditAction = "certificate_validated"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type CertificateStatus string

const (
	CertificateStatusActive  CertificateStatus = "active"
	CertificateStatusRevoked CertificateStatus = "revoked"
	CertificateStatusExpired CertificateStatus = "expired"
)

func (e *CertificateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CertificateStatus(s)
	case string:
		*e = CertificateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CertificateStatus: %T", src)
	}
	return nil
}

type NullCertificateStatus struct {
	CertificateStatus CertificateStatus `json:"certificate_status"`
	Valid             bool              `json:"valid"` // Valid is true if CertificateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCertificateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CertificateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CertificateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCertificateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CertificateStatus), nil
}

type CertificateType string

const (
	CertificateTypeUser         CertificateType = "user"
	CertificateTypeOrganization CertificateType = "organization"
	CertificateTypeTimestamp    CertificateType = "timestamp"
)

func (e *CertificateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CertificateType(s)
	case string:
		*e = CertificateType(s)
	default:
		return fmt.Errorf("unsupported scan type for CertificateType: %T", src)
	}
	return nil
}

type NullCertificateType struct {
	CertificateType CertificateType `json:"certificate_type"`
	Valid           bool            `json:"valid"` // Valid is true if CertificateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCertificateType) Scan(value interface{}) error {
	if value == nil {
		ns.CertificateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CertificateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCertificateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CertificateType), nil
}

type DocumentStatus string

const (
	DocumentStatusDraft      DocumentStatus = "draft"
	DocumentStatusPending    DocumentStatus = "pending"
	DocumentStatusInProgress DocumentStatus = "in_progress"
	DocumentStatusCompleted  DocumentStatus = "completed"
	DocumentStatusDeclined   DocumentStatus = "declined"
	DocumentStatusExpired    DocumentStatus = "expired"
	DocumentStatusVoided     DocumentStatus = "voided"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type FieldType string

const (
	FieldTypeSignature FieldType = "signature"
	FieldTypeInitials  FieldType = "initials"
	FieldTypeDate      FieldType = "date"
	FieldTypeText      FieldType = "text"
	FieldTypeCheckbox  FieldType = "checkbox"
)

func (e *FieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldType(s)
	case string:
		*e = FieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldType: %T", src)
	}
	return nil
}

type NullFieldType struct {
	FieldType FieldType `json:"field_type"`
	Valid     bool      `json:"valid"` // Valid is true if FieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldType), nil
}

type SignatureAlgorithm string

const (
	SignatureAlgorithmRSASHA256   SignatureAlgorithm = "RSA_SHA256"
	SignatureAlgorithmECDSASHA256 SignatureAlgorithm = "ECDSA_SHA256"
	SignatureAlgorithmRSASHA384   SignatureAlgorithm = "RSA_SHA384"
	SignatureAlgorithmECDSASHA384 SignatureAlgorithm = "ECDSA_SHA384"
)

func (e *SignatureAlgorithm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignatureAlgorithm(s)
	case string:
		*e = SignatureAlgorithm(s)
	default:
		return fmt.Errorf("unsupported scan type for SignatureAlgorithm: %T", src)
	}
	return nil
}

type NullSignatureAlgorithm struct {
	SignatureAlgorithm SignatureAlgorithm `json:"signature_algorithm"`
	Valid              bool               `json:"valid"` // Valid is true if SignatureAlgorithm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignatureAlgorithm) Scan(value interface{}) error {
	if value == nil {
		ns.SignatureAlgorithm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignatureAlgorithm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignatureAlgorithm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignatureAlgorithm), nil
}

type SignerStatus string

const (
	SignerStatusPending  SignerStatus = "pending"
	SignerStatusSent     SignerStatus = "sent"
	SignerStatusViewed   SignerStatus = "viewed"
	SignerStatusSigned   SignerStatus = "signed"
	SignerStatusDeclined SignerStatus = "declined"
	SignerStatusExpired  SignerStatus = "expired"
)

func (e *SignerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignerStatus(s)
	case string:
		*e = SignerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignerStatus: %T", src)
	}
	return nil
}

type NullSignerStatus struct {
	SignerStatus SignerStatus `json:"signer_status"`
	Valid        bool         `json:"valid"` // Valid is true if SignerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignerStatus), nil
}

type SignerType string

const (
	SignerTypeSigner   SignerType = "signer"
	SignerTypeApprover SignerType = "approver"
	SignerTypeCc       SignerType = "cc"
)

func (e *SignerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignerType(s)
	case string:
		*e = SignerType(s)
	default:
		return fmt.Errorf("unsupported scan type for SignerType: %T", src)
	}
	return nil
}

type NullSignerType struct {
	SignerType SignerType `json:"signer_type"`
	Valid      bool       `json:"valid"` // Valid is true if SignerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignerType) Scan(value interface{}) error {
	if value == nil {
		ns.SignerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignerType), nil
}

type AuditTrail struct {
	ID            string             `json:"id"`
	DocumentID    string             `json:"document_id"`
	SignerID      pgtype.Text        `json:"signer_id"`
	UserID        pgtype.Text        `json:"user_id"`
	Action        AuditAction        `json:"action"`
	ActionDetails []byte             `json:"action_details"`
	IpAddress     *netip.Addr        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	GeoLocation   pgtype.Text        `json:"geo_location"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID                    string             `json:"id"`
	OrganizationID        string             `json:"organization_id"`
	Name                  string             `json:"name"`
	Description           pgtype.Text        `json:"description"`
	Status                DocumentStatus     `json:"status"`
	StorageKey            string             `json:"storage_key"`
	SignedStorageKey      pgtype.Text        `json:"signed_storage_key"`
	TotalPages            int32              `json:"total_pages"`
	FileSizeBytes         pgtype.Int8        `json:"file_size_bytes"`
	MimeType              string             `json:"mime_type"`
	SigningOrder          bool               `json:"signing_order"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ReminderFrequencyDays pgtype.Int4        `json:"reminder_frequency_days"`
	CreatedBy             string             `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	Annotations           []byte             `json:"annotations"`
}

type Signature struct {
	ID                    string             `json:"id"`
	DocumentID            string             `json:"document_id"`
	SignerID              string             `json:"signer_id"`
	SignatureData         []byte             `json:"signature_data"`
	SignatureAlgorithm    SignatureAlgorithm `json:"signature_algorithm"`
	CertificateChain      string             `json:"certificate_chain"`
	SigningTimestamp      pgtype.Timestamptz `json:"signing_timestamp"`
	DocumentHash          string             `json:"document_hash"`
	DocumentHashAlgorithm string             `json:"document_hash_algorithm"`
	OcspResponse          []byte             `json:"ocsp_response"`
	TimestampToken        []byte             `json:"timestamp_token"`
	CertificateIssuer     pgtype.Text        `json:"certificate_issuer"`
	CertificateSerial     pgtype.Text        `json:"certificate_serial"`
	CertificateValidFrom  pgtype.Timestamptz `json:"certificate_valid_from"`
	CertificateValidTo    pgtype.Timestamptz `json:"certificate_valid_to"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SignatureField struct {
	ID          string             `json:"id"`
	DocumentID  string             `json:"document_id"`
	SignerID    string             `json:"signer_id"`
	FieldType   FieldType          `json:"field_type"`
	PageNumber  int32              `json:"page_number"`
	X           pgtype.Numeric     `json:"x"`
	Y           pgtype.Numeric     `json:"y"`
	Width       pgtype.Numeric     `json:"width"`
	Height      pgtype.Numeric     `json:"height"`
	Required    bool               `json:"required"`
	Label       pgtype.Text        `json:"label"`
	Placeholder pgtype.Text        `json:"placeholder"`
	Value       pgtype.Text        `json:"value"`
	FilledAt    pgtype.Timestamptz `json:"filled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FontSize    pgtype.Int4        `json:"font_size"`
}

type Signer struct {
	ID                   string             `json:"id"`
	DocumentID           string             `json:"document_id"`
	Email                string             `json:"email"`
	Name                 string             `json:"name"`
	UserID               pgtype.Text        `json:"user_id"`
	SignerType           SignerType         `json:"signer_type"`
	SigningOrder         int32              `json:"signing_order"`
	Status               SignerStatus       `json:"status"`
	AccessToken          pgtype.Text        `json:"access_token"`
	AccessTokenExpiresAt pgtype.Timestamptz `json:"access_token_expires_at"`
	EmailSentAt          pgtype.Timestamptz `json:"email_sent_at"`
	LastReminderAt       pgtype.Timestamptz `json:"last_reminder_at"`
	ViewedAt             pgtype.Timestamptz `json:"viewed_at"`
	SignedAt             pgtype.Timestamptz `json:"signed_at"`
	DeclinedAt           pgtype.Timestamptz `json:"declined_at"`
	DeclineReason        pgtype.Text        `json:"decline_reason"`
	SigningIpAddress     *netip.Addr        `json:"signing_ip_address"`
	SigningUserAgent     pgtype.Text        `json:"signing_user_agent"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SigningCertificate struct {
	ID                  string             `json:"id"`
	OrganizationID      string             `json:"organization_id"`
	UserID              pgtype.Text        `json:"user_id"`
	CertificateType     CertificateType    `json:"certificate_type"`
	Status              CertificateStatus  `json:"status"`
	CertificatePem      string             `json:"certificate_pem"`
	PrivateKeyEncrypted []byte             `json:"private_key_encrypted"`
	KeyEncryptionKeyID  string             `json:"key_encryption_key_id"`
	SerialNumber        string             `json:"serial_number"`
	IssuerDn            string             `json:"issuer_dn"`
	SubjectDn           string             `json:"subject_dn"`
	ValidFrom           pgtype.Timestamptz `json:"valid_from"`
	ValidTo             pgtype.Timestamptz `json:"valid_to"`
	CaName              string             `json:"ca_name"`
	CaCertificateChain  string             `json:"ca_certificate_chain"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason    pgtype.Text        `json:"revocation_reason"`
}

type Superadmin struct {
	Email     string             `json:"email"`
	GrantedBy string             `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}
