// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllDocuments(ctx context.Context) (int64, error)
	CountAuditEntries(ctx context.Context, documentID string) (int64, error)
	CountDocumentsByOrg(ctx context.Context, organizationID string) (int64, error)
	CountDocumentsByOrgAndStatus(ctx context.Context, arg CountDocumentsByOrgAndStatusParams) (int64, error)
	CountDocumentsForUser(ctx context.Context, lower string) (int32, error)
	CountFilledFieldsBySigner(ctx context.Context, signerID string) (int64, error)
	CountRequiredUnfilledFields(ctx context.Context, signerID string) (int64, error)
	CountSignaturesByDocument(ctx context.Context, documentID string) (int64, error)
	CountSignedSigners(ctx context.Context, documentID string) (int64, error)
	CountSignersByEmail(ctx context.Context, email string) (int64, error)
	CountSuperadmins(ctx context.Context) (int32, error)
	CountTotalSigners(ctx context.Context, documentID string) (int64, error)
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditTrail, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error)
	CreateSignatureField(ctx context.Context, arg CreateSignatureFieldParams) (SignatureField, error)
	CreateSigner(ctx context.Context, arg CreateSignerParams) (Signer, error)
	CreateSigningCertificate(ctx context.Context, arg CreateSigningCertificateParams) (SigningCertificate, error)
	DeleteDocument(ctx context.Context, id string) error
	DeleteSignatureField(ctx context.Context, id string) error
	DeleteSignatureFieldsBySigner(ctx context.Context, signerID string) error
	DeleteSigner(ctx context.Context, id string) error
	FillSignatureField(ctx context.Context, arg FillSignatureFieldParams) (SignatureField, error)
	GetActiveCertificateByOrg(ctx context.Context, organizationID string) (SigningCertificate, error)
	GetActiveCertificateByUser(ctx context.Context, userID pgtype.Text) (SigningCertificate, error)
	GetAuditEntriesByAction(ctx context.Context, arg GetAuditEntriesByActionParams) ([]AuditTrail, error)
	GetAuditEntriesBySigner(ctx context.Context, signerID pgtype.Text) ([]AuditTrail, error)
	GetAuditTrail(ctx context.Context, arg GetAuditTrailParams) ([]AuditTrail, error)
	GetDocument(ctx context.Context, id string) (Document, error)
	GetDocumentAnnotations(ctx context.Context, id string) ([]byte, error)
	GetDocumentByOrg(ctx context.Context, arg GetDocumentByOrgParams) (Document, error)
	GetExpiredCertificates(ctx context.Context) ([]SigningCertificate, error)
	GetExpiredDocuments(ctx context.Context) ([]Document, error)
	GetNextSigner(ctx context.Context, documentID string) (Signer, error)
	GetPendingSignersByDocument(ctx context.Context, documentID string) ([]Signer, error)
	GetSignature(ctx context.Context, id string) (Signature, error)
	GetSignatureByDocumentAndSigner(ctx context.Context, arg GetSignatureByDocumentAndSignerParams) (Signature, error)
	GetSignatureField(ctx context.Context, id string) (SignatureField, error)
	GetSignatureFieldsByDocument(ctx context.Context, documentID string) ([]SignatureField, error)
	GetSignatureFieldsBySigner(ctx context.Context, signerID string) ([]SignatureField, error)
	GetSignaturesByDocument(ctx context.Context, documentID string) ([]Signature, error)
	GetSigner(ctx context.Context, id string) (Signer, error)
	GetSignerByToken(ctx context.Context, accessToken pgtype.Text) (Signer, error)
	GetSignersByDocument(ctx context.Context, documentID string) ([]Signer, error)
	GetSignersByEmail(ctx context.Context, arg GetSignersByEmailParams) ([]Signer, error)
	GetSigningCertificate(ctx context.Context, id string) (SigningCertificate, error)
	GrantSuperadmin(ctx context.Context, arg GrantSuperadminParams) error
	IsSuperadmin(ctx context.Context, lower string) (bool, error)
	ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]Document, error)
	ListCertificatesByOrg(ctx context.Context, organizationID string) ([]SigningCertificate, error)
	ListDocumentsByOrg(ctx context.Context, arg ListDocumentsByOrgParams) ([]Document, error)
	ListDocumentsByOrgAndStatus(ctx context.Context, arg ListDocumentsByOrgAndStatusParams) ([]Document, error)
	ListDocumentsForUser(ctx context.Context, arg ListDocumentsForUserParams) ([]Document, error)
	ListSuperadmins(ctx context.Context) ([]Superadmin, error)
	RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (SigningCertificate, error)
	RevokeSuperadmin(ctx context.Context, lower string) error
	SetSignerAccessToken(ctx context.Context, arg SetSignerAccessTokenParams) (Signer, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentAnnotations(ctx context.Context, arg UpdateDocumentAnnotationsParams) error
	UpdateDocumentCompleted(ctx context.Context, arg UpdateDocumentCompletedParams) (Document, error)
	UpdateDocumentPageCount(ctx context.Context, arg UpdateDocumentPageCountParams) (Document, error)
	UpdateDocumentSignedKey(ctx context.Context, arg UpdateDocumentSignedKeyParams) (Document, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
	UpdateSignatureField(ctx context.Context, arg UpdateSignatureFieldParams) (SignatureField, error)
	UpdateSigner(ctx context.Context, arg UpdateSignerParams) (Signer, error)
	UpdateSignerDeclined(ctx context.Context, arg UpdateSignerDeclinedParams) (Signer, error)
	UpdateSignerEmailSent(ctx context.Context, id string) (Signer, error)
	UpdateSignerReminder(ctx context.Context, id string) (Signer, error)
	UpdateSignerSent(ctx context.Context, id string) (Signer, error)
	UpdateSignerSigned(ctx context.Context, arg UpdateSignerSignedParams) (Signer, error)
	UpdateSignerStatus(ctx context.Context, arg UpdateSignerStatusParams) (Signer, error)
	UpdateSignerViewed(ctx context.Context, id string) (Signer, error)

	// Template queries
	CountTemplates(ctx context.Context, organizationID string) (int64, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (DocumentTemplate, error)
	CreateTemplateField(ctx context.Context, arg CreateTemplateFieldParams) (TemplateField, error)
	DeleteTemplate(ctx context.Context, id string) error
	DeleteTemplateFields(ctx context.Context, templateID string) error
	GetTemplate(ctx context.Context, id string) (DocumentTemplate, error)
	GetTemplateByOrg(ctx context.Context, arg GetTemplateByOrgParams) (DocumentTemplate, error)
	GetTemplateFields(ctx context.Context, templateID string) ([]TemplateField, error)
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]DocumentTemplate, error)
}

var _ Querier = (*Queries)(nil)
