// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signatures.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignaturesByDocument = `-- name: CountSignaturesByDocument :one
SELECT COUNT(*) FROM signatures WHERE document_id = $1
`

func (q *Queries) CountSignaturesByDocument(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSignaturesByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSignature = `-- name: CreateSignature :one
INSERT INTO signatures (
    id, document_id, signer_id, signature_data, signature_algorithm,
    certificate_chain, signing_timestamp, document_hash, document_hash_algorithm,
    ocsp_response, timestamp_token, certificate_issuer, certificate_serial,
    certificate_valid_from, certificate_valid_to
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, document_id, signer_id, signature_data, signature_algorithm, certificate_chain, signing_timestamp, document_hash, document_hash_algorithm, ocsp_response, timestamp_token, certificate_issuer, certificate_serial, certificate_valid_from, certificate_valid_to, created_at
`

type CreateSignatureParams struct {
	ID                    string             `json:"id"`
	DocumentID            string             `json:"document_id"`
	SignerID              string             `json:"signer_id"`
	SignatureData         []byte             `json:"signature_data"`
	SignatureAlgorithm    SignatureAlgorithm `json:"signature_algorithm"`
	CertificateChain      string             `json:"certificate_chain"`
	SigningTimestamp      pgtype.Timestamptz `json:"signing_timestamp"`
	DocumentHash          string             `json:"document_hash"`
	DocumentHashAlgorithm string             `json:"document_hash_algorithm"`
	OcspResponse          []byte             `json:"ocsp_response"`
	TimestampToken        []byte             `json:"timestamp_token"`
	CertificateIssuer     pgtype.Text        `json:"certificate_issuer"`
	CertificateSerial     pgtype.Text        `json:"certificate_serial"`
	CertificateValidFrom  pgtype.Timestamptz `json:"certificate_valid_from"`
	CertificateValidTo    pgtype.Timestamptz `json:"certificate_valid_to"`
}

func (q *Queries) CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error) {
	row := q.db.QueryRow(ctx, createSignature,
		arg.ID,
		arg.DocumentID,
		arg.SignerID,
		arg.SignatureData,
		arg.SignatureAlgorithm,
		arg.CertificateChain,
		arg.SigningTimestamp,
		arg.DocumentHash,
		arg.DocumentHashAlgorithm,
		arg.OcspResponse,
		arg.TimestampToken,
		arg.CertificateIssuer,
		arg.CertificateSerial,
		arg.CertificateValidFrom,
		arg.CertificateValidTo,
	)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.SignatureData,
		&i.SignatureAlgorithm,
		&i.CertificateChain,
		&i.SigningTimestamp,
		&i.DocumentHash,
		&i.DocumentHashAlgorithm,
		&i.OcspResponse,
		&i.TimestampToken,
		&i.CertificateIssuer,
		&i.CertificateSerial,
		&i.CertificateValidFrom,
		&i.CertificateValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const getSignature = `-- name: GetSignature :one
SELECT id, document_id, signer_id, signature_data, signature_algorithm, certificate_chain, signing_timestamp, document_hash, document_hash_algorithm, ocsp_response, timestamp_token, certificate_issuer, certificate_serial, certificate_valid_from, certificate_valid_to, created_at FROM signatures WHERE id = $1
`

func (q *Queries) GetSignature(ctx context.Context, id string) (Signature, error) {
	row := q.db.QueryRow(ctx, getSignature, id)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.SignatureData,
		&i.SignatureAlgorithm,
		&i.CertificateChain,
		&i.SigningTimestamp,
		&i.DocumentHash,
		&i.DocumentHashAlgorithm,
		&i.OcspResponse,
		&i.TimestampToken,
		&i.CertificateIssuer,
		&i.CertificateSerial,
		&i.CertificateValidFrom,
		&i.CertificateValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const getSignatureByDocumentAndSigner = `-- name: GetSignatureByDocumentAndSigner :one
SELECT id, document_id, signer_id, signature_data, signature_algorithm, certificate_chain, signing_timestamp, document_hash, document_hash_algorithm, ocsp_response, timestamp_token, certificate_issuer, certificate_serial, certificate_valid_from, certificate_valid_to, created_at FROM signatures WHERE document_id = $1 AND signer_id = $2
`

type GetSignatureByDocumentAndSignerParams struct {
	DocumentID string `json:"document_id"`
	SignerID   string `json:"signer_id"`
}

func (q *Queries) GetSignatureByDocumentAndSigner(ctx context.Context, arg GetSignatureByDocumentAndSignerParams) (Signature, error) {
	row := q.db.QueryRow(ctx, getSignatureByDocumentAndSigner, arg.DocumentID, arg.SignerID)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.SignatureData,
		&i.SignatureAlgorithm,
		&i.CertificateChain,
		&i.SigningTimestamp,
		&i.DocumentHash,
		&i.DocumentHashAlgorithm,
		&i.OcspResponse,
		&i.TimestampToken,
		&i.CertificateIssuer,
		&i.CertificateSerial,
		&i.CertificateValidFrom,
		&i.CertificateValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const getSignaturesByDocument = `-- name: GetSignaturesByDocument :many
SELECT id, document_id, signer_id, signature_data, signature_algorithm, certificate_chain, signing_timestamp, document_hash, document_hash_algorithm, ocsp_response, timestamp_token, certificate_issuer, certificate_serial, certificate_valid_from, certificate_valid_to, created_at FROM signatures
WHERE document_id = $1
ORDER BY signing_timestamp ASC
`

func (q *Queries) GetSignaturesByDocument(ctx context.Context, documentID string) ([]Signature, error) {
	rows, err := q.db.Query(ctx, getSignaturesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signature{}
	for rows.Next() {
		var i Signature
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.SignatureData,
			&i.SignatureAlgorithm,
			&i.CertificateChain,
			&i.SigningTimestamp,
			&i.DocumentHash,
			&i.DocumentHashAlgorithm,
			&i.OcspResponse,
			&i.TimestampToken,
			&i.CertificateIssuer,
			&i.CertificateSerial,
			&i.CertificateValidFrom,
			&i.CertificateValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
