// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signature_fields.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilledFieldsBySigner = `-- name: CountFilledFieldsBySigner :one
SELECT COUNT(*) FROM signature_fields
WHERE signer_id = $1 AND value IS NOT NULL
`

func (q *Queries) CountFilledFieldsBySigner(ctx context.Context, signerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFilledFieldsBySigner, signerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequiredUnfilledFields = `-- name: CountRequiredUnfilledFields :one
SELECT COUNT(*) FROM signature_fields
WHERE signer_id = $1 AND required = true AND value IS NULL
`

func (q *Queries) CountRequiredUnfilledFields(ctx context.Context, signerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRequiredUnfilledFields, signerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSignatureField = `-- name: CreateSignatureField :one
INSERT INTO signature_fields (
    id, document_id, signer_id, field_type, page_number,
    x, y, width, height, required, label, placeholder, font_size
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size
`

type CreateSignatureFieldParams struct {
	ID          string         `json:"id"`
	DocumentID  string         `json:"document_id"`
	SignerID    string         `json:"signer_id"`
	FieldType   FieldType      `json:"field_type"`
	PageNumber  int32          `json:"page_number"`
	X           pgtype.Numeric `json:"x"`
	Y           pgtype.Numeric `json:"y"`
	Width       pgtype.Numeric `json:"width"`
	Height      pgtype.Numeric `json:"height"`
	Required    bool           `json:"required"`
	Label       pgtype.Text    `json:"label"`
	Placeholder pgtype.Text    `json:"placeholder"`
	FontSize    pgtype.Int4    `json:"font_size"`
}

func (q *Queries) CreateSignatureField(ctx context.Context, arg CreateSignatureFieldParams) (SignatureField, error) {
	row := q.db.QueryRow(ctx, createSignatureField,
		arg.ID,
		arg.DocumentID,
		arg.SignerID,
		arg.FieldType,
		arg.PageNumber,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Required,
		arg.Label,
		arg.Placeholder,
		arg.FontSize,
	)
	var i SignatureField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.FieldType,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Placeholder,
		&i.Value,
		&i.FilledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FontSize,
	)
	return i, err
}

const deleteSignatureField = `-- name: DeleteSignatureField :exec
DELETE FROM signature_fields WHERE id = $1
`

func (q *Queries) DeleteSignatureField(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSignatureField, id)
	return err
}

const deleteSignatureFieldsBySigner = `-- name: DeleteSignatureFieldsBySigner :exec
DELETE FROM signature_fields WHERE signer_id = $1
`

func (q *Queries) DeleteSignatureFieldsBySigner(ctx context.Context, signerID string) error {
	_, err := q.db.Exec(ctx, deleteSignatureFieldsBySigner, signerID)
	return err
}

const fillSignatureField = `-- name: FillSignatureField :one
UPDATE signature_fields
SET value = $2, filled_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size
`

type FillSignatureFieldParams struct {
	ID    string      `json:"id"`
	Value pgtype.Text `json:"value"`
}

func (q *Queries) FillSignatureField(ctx context.Context, arg FillSignatureFieldParams) (SignatureField, error) {
	row := q.db.QueryRow(ctx, fillSignatureField, arg.ID, arg.Value)
	var i SignatureField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.FieldType,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Placeholder,
		&i.Value,
		&i.FilledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FontSize,
	)
	return i, err
}

const getSignatureField = `-- name: GetSignatureField :one
SELECT id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size FROM signature_fields WHERE id = $1
`

func (q *Queries) GetSignatureField(ctx context.Context, id string) (SignatureField, error) {
	row := q.db.QueryRow(ctx, getSignatureField, id)
	var i SignatureField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.FieldType,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Placeholder,
		&i.Value,
		&i.FilledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FontSize,
	)
	return i, err
}

const getSignatureFieldsByDocument = `-- name: GetSignatureFieldsByDocument :many
SELECT id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size FROM signature_fields
WHERE document_id = $1
ORDER BY page_number ASC, y ASC
`

func (q *Queries) GetSignatureFieldsByDocument(ctx context.Context, documentID string) ([]SignatureField, error) {
	rows, err := q.db.Query(ctx, getSignatureFieldsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignatureField{}
	for rows.Next() {
		var i SignatureField
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.FieldType,
			&i.PageNumber,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Required,
			&i.Label,
			&i.Placeholder,
			&i.Value,
			&i.FilledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FontSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignatureFieldsBySigner = `-- name: GetSignatureFieldsBySigner :many
SELECT id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size FROM signature_fields
WHERE signer_id = $1
ORDER BY page_number ASC, y ASC
`

func (q *Queries) GetSignatureFieldsBySigner(ctx context.Context, signerID string) ([]SignatureField, error) {
	rows, err := q.db.Query(ctx, getSignatureFieldsBySigner, signerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignatureField{}
	for rows.Next() {
		var i SignatureField
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SignerID,
			&i.FieldType,
			&i.PageNumber,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Required,
			&i.Label,
			&i.Placeholder,
			&i.Value,
			&i.FilledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FontSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSignatureField = `-- name: UpdateSignatureField :one
UPDATE signature_fields
SET page_number = $2, x = $3, y = $4, width = $5, height = $6, label = $7, font_size = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, signer_id, field_type, page_number, x, y, width, height, required, label, placeholder, value, filled_at, created_at, updated_at, font_size
`

type UpdateSignatureFieldParams struct {
	ID         string         `json:"id"`
	PageNumber int32          `json:"page_number"`
	X          pgtype.Numeric `json:"x"`
	Y          pgtype.Numeric `json:"y"`
	Width      pgtype.Numeric `json:"width"`
	Height     pgtype.Numeric `json:"height"`
	Label      pgtype.Text    `json:"label"`
	FontSize   pgtype.Int4    `json:"font_size"`
}

func (q *Queries) UpdateSignatureField(ctx context.Context, arg UpdateSignatureFieldParams) (SignatureField, error) {
	row := q.db.QueryRow(ctx, updateSignatureField,
		arg.ID,
		arg.PageNumber,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Label,
		arg.FontSize,
	)
	var i SignatureField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SignerID,
		&i.FieldType,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Placeholder,
		&i.Value,
		&i.FilledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FontSize,
	)
	return i, err
}
