// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signers.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignedSigners = `-- name: CountSignedSigners :one
SELECT COUNT(*) FROM signers WHERE document_id = $1 AND status = 'signed'
`

func (q *Queries) CountSignedSigners(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSignedSigners, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignersByEmail = `-- name: CountSignersByEmail :one
SELECT COUNT(*) FROM signers s
JOIN documents d ON d.id = s.document_id
WHERE s.email = $1
AND s.status IN ('pending', 'viewed')
AND d.status IN ('pending', 'in_progress')
`

func (q *Queries) CountSignersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countSignersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalSigners = `-- name: CountTotalSigners :one
SELECT COUNT(*) FROM signers WHERE document_id = $1 AND signer_type = 'signer'
`

func (q *Queries) CountTotalSigners(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalSigners, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSigner = `-- name: CreateSigner :one
INSERT INTO signers (
    id, document_id, email, name, user_id, signer_type, signing_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type CreateSignerParams struct {
	ID           string      `json:"id"`
	DocumentID   string      `json:"document_id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	UserID       pgtype.Text `json:"user_id"`
	SignerType   SignerType  `json:"signer_type"`
	SigningOrder int32       `json:"signing_order"`
}

func (q *Queries) CreateSigner(ctx context.Context, arg CreateSignerParams) (Signer, error) {
	row := q.db.QueryRow(ctx, createSigner,
		arg.ID,
		arg.DocumentID,
		arg.Email,
		arg.Name,
		arg.UserID,
		arg.SignerType,
		arg.SigningOrder,
	)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSigner = `-- name: DeleteSigner :exec
DELETE FROM signers WHERE id = $1
`

func (q *Queries) DeleteSigner(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSigner, id)
	return err
}

const getNextSigner = `-- name: GetNextSigner :one
SELECT id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at FROM signers
WHERE document_id = $1 AND status IN ('pending', 'viewed')
ORDER BY signing_order ASC
LIMIT 1
`

func (q *Queries) GetNextSigner(ctx context.Context, documentID string) (Signer, error) {
	row := q.db.QueryRow(ctx, getNextSigner, documentID)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSignersByDocument = `-- name: GetPendingSignersByDocument :many
SELECT id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at FROM signers
WHERE document_id = $1 AND status IN ('pending', 'viewed')
ORDER BY signing_order ASC
`

func (q *Queries) GetPendingSignersByDocument(ctx context.Context, documentID string) ([]Signer, error) {
	rows, err := q.db.Query(ctx, getPendingSignersByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signer{}
	for rows.Next() {
		var i Signer
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Email,
			&i.Name,
			&i.UserID,
			&i.SignerType,
			&i.SigningOrder,
			&i.Status,
			&i.AccessToken,
			&i.AccessTokenExpiresAt,
			&i.EmailSentAt,
			&i.LastReminderAt,
			&i.ViewedAt,
			&i.SignedAt,
			&i.DeclinedAt,
			&i.DeclineReason,
			&i.SigningIpAddress,
			&i.SigningUserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigner = `-- name: GetSigner :one
SELECT id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at FROM signers WHERE id = $1
`

func (q *Queries) GetSigner(ctx context.Context, id string) (Signer, error) {
	row := q.db.QueryRow(ctx, getSigner, id)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignerByToken = `-- name: GetSignerByToken :one
SELECT id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at FROM signers
WHERE access_token = $1
AND access_token_expires_at > NOW()
`

func (q *Queries) GetSignerByToken(ctx context.Context, accessToken pgtype.Text) (Signer, error) {
	row := q.db.QueryRow(ctx, getSignerByToken, accessToken)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignersByDocument = `-- name: GetSignersByDocument :many
SELECT id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at FROM signers
WHERE document_id = $1
ORDER BY signing_order ASC
`

func (q *Queries) GetSignersByDocument(ctx context.Context, documentID string) ([]Signer, error) {
	rows, err := q.db.Query(ctx, getSignersByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signer{}
	for rows.Next() {
		var i Signer
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Email,
			&i.Name,
			&i.UserID,
			&i.SignerType,
			&i.SigningOrder,
			&i.Status,
			&i.AccessToken,
			&i.AccessTokenExpiresAt,
			&i.EmailSentAt,
			&i.LastReminderAt,
			&i.ViewedAt,
			&i.SignedAt,
			&i.DeclinedAt,
			&i.DeclineReason,
			&i.SigningIpAddress,
			&i.SigningUserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignersByEmail = `-- name: GetSignersByEmail :many
SELECT s.id, s.document_id, s.email, s.name, s.user_id, s.signer_type, s.signing_order, s.status, s.access_token, s.access_token_expires_at, s.email_sent_at, s.last_reminder_at, s.viewed_at, s.signed_at, s.declined_at, s.decline_reason, s.signing_ip_address, s.signing_user_agent, s.created_at, s.updated_at FROM signers s
JOIN documents d ON d.id = s.document_id
WHERE s.email = $1
AND s.status IN ('pending', 'viewed')
AND d.status IN ('pending', 'in_progress')
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type GetSignersByEmailParams struct {
	Email  string `json:"email"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetSignersByEmail(ctx context.Context, arg GetSignersByEmailParams) ([]Signer, error) {
	rows, err := q.db.Query(ctx, getSignersByEmail, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signer{}
	for rows.Next() {
		var i Signer
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Email,
			&i.Name,
			&i.UserID,
			&i.SignerType,
			&i.SigningOrder,
			&i.Status,
			&i.AccessToken,
			&i.AccessTokenExpiresAt,
			&i.EmailSentAt,
			&i.LastReminderAt,
			&i.ViewedAt,
			&i.SignedAt,
			&i.DeclinedAt,
			&i.DeclineReason,
			&i.SigningIpAddress,
			&i.SigningUserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSignerAccessToken = `-- name: SetSignerAccessToken :one
UPDATE signers
SET access_token = $2, access_token_expires_at = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type SetSignerAccessTokenParams struct {
	ID                   string             `json:"id"`
	AccessToken          pgtype.Text        `json:"access_token"`
	AccessTokenExpiresAt pgtype.Timestamptz `json:"access_token_expires_at"`
}

func (q *Queries) SetSignerAccessToken(ctx context.Context, arg SetSignerAccessTokenParams) (Signer, error) {
	row := q.db.QueryRow(ctx, setSignerAccessToken, arg.ID, arg.AccessToken, arg.AccessTokenExpiresAt)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSigner = `-- name: UpdateSigner :one
UPDATE signers
SET name = $2, email = $3, signer_type = $4, signing_order = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type UpdateSignerParams struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	SignerType   SignerType `json:"signer_type"`
	SigningOrder int32      `json:"signing_order"`
}

func (q *Queries) UpdateSigner(ctx context.Context, arg UpdateSignerParams) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSigner,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.SignerType,
		arg.SigningOrder,
	)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerDeclined = `-- name: UpdateSignerDeclined :one
UPDATE signers
SET status = 'declined', declined_at = NOW(), decline_reason = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type UpdateSignerDeclinedParams struct {
	ID            string      `json:"id"`
	DeclineReason pgtype.Text `json:"decline_reason"`
}

func (q *Queries) UpdateSignerDeclined(ctx context.Context, arg UpdateSignerDeclinedParams) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerDeclined, arg.ID, arg.DeclineReason)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerEmailSent = `-- name: UpdateSignerEmailSent :one
UPDATE signers
SET email_sent_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

func (q *Queries) UpdateSignerEmailSent(ctx context.Context, id string) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerEmailSent, id)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerReminder = `-- name: UpdateSignerReminder :one
UPDATE signers
SET last_reminder_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

func (q *Queries) UpdateSignerReminder(ctx context.Context, id string) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerReminder, id)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerSigned = `-- name: UpdateSignerSigned :one
UPDATE signers
SET status = 'signed', signed_at = NOW(), signing_ip_address = $2, signing_user_agent = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type UpdateSignerSignedParams struct {
	ID               string      `json:"id"`
	SigningIpAddress *netip.Addr `json:"signing_ip_address"`
	SigningUserAgent pgtype.Text `json:"signing_user_agent"`
}

func (q *Queries) UpdateSignerSigned(ctx context.Context, arg UpdateSignerSignedParams) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerSigned, arg.ID, arg.SigningIpAddress, arg.SigningUserAgent)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerStatus = `-- name: UpdateSignerStatus :one
UPDATE signers
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

type UpdateSignerStatusParams struct {
	ID     string       `json:"id"`
	Status SignerStatus `json:"status"`
}

func (q *Queries) UpdateSignerStatus(ctx context.Context, arg UpdateSignerStatusParams) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerStatus, arg.ID, arg.Status)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerSent = `-- name: UpdateSignerSent :one
UPDATE signers
SET status = 'sent', email_sent_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

func (q *Queries) UpdateSignerSent(ctx context.Context, id string) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerSent, id)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignerViewed = `-- name: UpdateSignerViewed :one
UPDATE signers
SET status = 'viewed', viewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'sent')
RETURNING id, document_id, email, name, user_id, signer_type, signing_order, status, access_token, access_token_expires_at, email_sent_at, last_reminder_at, viewed_at, signed_at, declined_at, decline_reason, signing_ip_address, signing_user_agent, created_at, updated_at
`

func (q *Queries) UpdateSignerViewed(ctx context.Context, id string) (Signer, error) {
	row := q.db.QueryRow(ctx, updateSignerViewed, id)
	var i Signer
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Email,
		&i.Name,
		&i.UserID,
		&i.SignerType,
		&i.SigningOrder,
		&i.Status,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.EmailSentAt,
		&i.LastReminderAt,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.SigningIpAddress,
		&i.SigningUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
