// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: superadmins.sql

package sqlc

import (
	"context"
)

const countSuperadmins = `-- name: CountSuperadmins :one
SELECT count(*)::int FROM superadmins
`

func (q *Queries) CountSuperadmins(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countSuperadmins)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const grantSuperadmin = `-- name: GrantSuperadmin :exec
INSERT INTO superadmins (email, granted_by) VALUES (lower($1), $2)
ON CONFLICT (email) DO NOTHING
`

type GrantSuperadminParams struct {
	Lower     string `json:"lower"`
	GrantedBy string `json:"granted_by"`
}

func (q *Queries) GrantSuperadmin(ctx context.Context, arg GrantSuperadminParams) error {
	_, err := q.db.Exec(ctx, grantSuperadmin, arg.Lower, arg.GrantedBy)
	return err
}

const isSuperadmin = `-- name: IsSuperadmin :one
SELECT EXISTS (SELECT 1 FROM superadmins WHERE lower(email) = lower($1))
`

func (q *Queries) IsSuperadmin(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, isSuperadmin, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSuperadmins = `-- name: ListSuperadmins :many
SELECT email, granted_by, granted_at FROM superadmins ORDER BY granted_at ASC
`

func (q *Queries) ListSuperadmins(ctx context.Context) ([]Superadmin, error) {
	rows, err := q.db.Query(ctx, listSuperadmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Superadmin{}
	for rows.Next() {
		var i Superadmin
		if err := rows.Scan(&i.Email, &i.GrantedBy, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSuperadmin = `-- name: RevokeSuperadmin :exec
DELETE FROM superadmins WHERE lower(email) = lower($1)
`

func (q *Queries) RevokeSuperadmin(ctx context.Context, lower string) error {
	_, err := q.db.Exec(ctx, revokeSuperadmin, lower)
	return err
}
