import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import {
  BASE_URL,
  createDeck,
  getDeckData,
  saveDeckData,
  trashDeck,
} from "./helpers";

// pptx round trip through the UI: a deck is exported with File ▸ Download ▸
// .pptx (so the fixture is generated by our own writer, never checked in),
// then imported back two ways — Slides home "Upload .pptx" (new deck) and
// File ▸ Import slides (append) — and the imported slides must render.

const SOURCE = {
  slides: [
    {
      id: "s1",
      background: "#e8f0fe",
      notes: "Opening remarks",
      transition: "fade",
      elements: [
        {
          id: "t1",
          type: "text",
          x: 80,
          y: 180,
          w: 800,
          h: 100,
          text: "Imported title",
          fontSize: 44,
          bold: true,
          color: "#1a73e8",
          align: "center",
          valign: "middle",
          fontFamily: "Arial",
        },
      ],
    },
    {
      id: "s2",
      background: "#ffffff",
      elements: [
        { id: "r", type: "rect", x: 80, y: 80, w: 200, h: 120, fill: "#34a853", stroke: "none", strokeWidth: 0 },
        { id: "e", type: "ellipse", x: 320, y: 80, w: 200, h: 120, fill: "#fbbc04", stroke: "#202124", strokeWidth: 2, rotation: 20 },
        {
          id: "t2",
          type: "text",
          x: 80,
          y: 260,
          w: 600,
          h: 160,
          text: "First point\nSecond point",
          list: "bullet",
          fontSize: 24,
          color: "#202124",
          align: "left",
          valign: "top",
          fontFamily: "Arial",
        },
      ],
    },
    {
      id: "s3",
      background: "#ffffff",
      elements: [
        {
          id: "tb",
          type: "table",
          x: 80,
          y: 80,
          w: 480,
          h: 120,
          table: { rows: 2, cols: 2, cells: [["Region", "Sales"], ["North", "42"]] },
          fill: "none",
          stroke: "#bdc1c6",
          strokeWidth: 1,
          fontSize: 16,
          color: "#202124",
          fontFamily: "Arial",
        },
      ],
    },
  ],
};

async function openDeck(page: Page, id: string) {
  await page.goto(`${BASE_URL}/slides/d/${id}`);
  await expect(page.getByRole("textbox", { name: "Presentation title" })).toBeVisible();
}

async function downloadPptx(page: Page): Promise<Buffer> {
  await page.getByRole("button", { name: "File", exact: true }).click();
  await page.getByText("Download", { exact: true }).click();
  const dl = page.waitForEvent("download");
  await page.getByRole("menuitem", { name: /Microsoft PowerPoint/ }).click();
  const file = await (await dl).path();
  return readFile(file);
}

test.describe.serial("slides pptx", () => {
  test("export to pptx, upload it as a new deck, and import slides into a deck", async ({ page }, testInfo) => {
    const sourceId = await createDeck(page.request, "e2e pptx source");
    let importedId: string | undefined;
    try {
      await saveDeckData(page.request, sourceId, SOURCE);
      await openDeck(page, sourceId);
      await expect(page.getByTestId("slide-thumb")).toHaveCount(3);

      const pptx = await downloadPptx(page);
      expect(pptx.subarray(0, 2).toString()).toBe("PK");

      // 1) Slides home ▸ Upload .pptx → a new deck opens with the slides.
      await page.goto(`${BASE_URL}/slides`);
      await page.getByTestId("pptx-upload-input").setInputFiles({
        name: "e2e-roundtrip.pptx",
        mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        buffer: pptx,
      });
      await page.waitForURL(/\/slides\/d\/[^/]+$/);
      importedId = page.url().split("/").pop();
      expect(importedId).not.toBe(sourceId);
      await expect(page.getByRole("textbox", { name: "Presentation title" })).toHaveValue("e2e pptx source");
      await expect(page.getByTestId("slide-thumb")).toHaveCount(3);
      await expect(page.getByTestId("slide-thumb").first()).toContainText("Imported title");
      await expect(page.getByTestId("slide-thumb").nth(1)).toContainText("Second point");
      await expect(page.getByTestId("slide-thumb").nth(2)).toContainText("North");

      const shot = process.env.SLIDES_PPTX_SCREENSHOT ?? testInfo.outputPath("imported-deck.png");
      await page.screenshot({ path: shot, fullPage: false });

      const data = (await getDeckData(page.request, importedId!)) as {
        slides: { elements: { type: string; text?: string; table?: { cells: string[][] } }[]; notes?: string; transition?: string; background: string }[];
      };
      expect(data.slides).toHaveLength(3);
      expect(data.slides[0].notes).toBe("Opening remarks");
      expect(data.slides[0].transition).toBe("fade");
      expect(data.slides[0].background).toBe("#e8f0fe");
      expect(data.slides[1].elements.map((e) => e.type)).toEqual(["rect", "ellipse", "text"]);
      expect(data.slides[2].elements[0].table?.cells).toEqual([["Region", "Sales"], ["North", "42"]]);

      // 2) File ▸ Import slides appends to the open deck.
      await page.getByRole("button", { name: "File", exact: true }).click();
      await expect(page.getByRole("menuitem", { name: "Import slides (.pptx)" })).toBeVisible();
      await page.keyboard.press("Escape");
      await page.getByTestId("pptx-import-input").setInputFiles({
        name: "more.pptx",
        mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        buffer: pptx,
      });
      await expect(page.getByTestId("pptx-import-status")).toContainText("Imported 3 slides");
      await expect(page.getByTestId("slide-thumb")).toHaveCount(6);
      await expect(async () => {
        const after = await getDeckData(page.request, importedId!);
        expect(after?.slides).toHaveLength(6);
      }).toPass({ timeout: 15_000 });
    } finally {
      await trashDeck(page.request, sourceId);
      if (importedId) await trashDeck(page.request, importedId);
    }
  });
});
