package calendar

import (
	"sort"
	"strconv"
	"strings"
	"time"
)

// Recurrence expansion.
//
// Events store a small RRULE-style string in the `recurrence` column. We
// support the subset surfaced by the event dialog:
//
//	FREQ=DAILY                       — every day
//	FREQ=WEEKLY;BYDAY=MO,WE,FR       — weekly on the given weekdays
//	FREQ=WEEKLY                      — weekly on the master event's weekday
//	FREQ=MONTHLY                     — monthly on the master event's day-of-month
//	FREQ=YEARLY                      — annually on the master event's month/day
//	FREQ=WEEKDAY                     — every weekday (Mon–Fri); shorthand
//	INTERVAL=n                       — repeat every n periods (default 1)
//	UNTIL=2026-12-31T00:00:00Z       — optional inclusive end bound (RFC3339)
//	COUNT=n                          — optional max number of occurrences
//
// An empty/blank recurrence string means the event does not repeat.

// maxOccurrences caps expansion so a pathological rule + huge window cannot
// produce an unbounded slice.
const maxOccurrences = 1000

type recRule struct {
	freq     string // DAILY | WEEKLY | MONTHLY | YEARLY | WEEKDAY
	interval int
	byDay    map[time.Weekday]bool // for WEEKLY
	until    time.Time
	hasUntil bool
	count    int // 0 = unbounded
}

var weekdayCodes = map[string]time.Weekday{
	"SU": time.Sunday, "MO": time.Monday, "TU": time.Tuesday, "WE": time.Wednesday,
	"TH": time.Thursday, "FR": time.Friday, "SA": time.Saturday,
}

// parseRecurrence parses an RRULE-subset string. ok is false for blank or
// unrecognised rules (treated as "does not repeat").
func parseRecurrence(s string) (recRule, bool) {
	s = strings.TrimSpace(s)
	if s == "" {
		return recRule{}, false
	}
	// Tolerate a leading "RRULE:" prefix (iCalendar style).
	s = strings.TrimPrefix(s, "RRULE:")
	r := recRule{interval: 1}
	for _, part := range strings.Split(s, ";") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		kv := strings.SplitN(part, "=", 2)
		if len(kv) != 2 {
			continue
		}
		key := strings.ToUpper(strings.TrimSpace(kv[0]))
		val := strings.TrimSpace(kv[1])
		switch key {
		case "FREQ":
			r.freq = strings.ToUpper(val)
		case "INTERVAL":
			if n, err := strconv.Atoi(val); err == nil && n > 0 {
				r.interval = n
			}
		case "BYDAY":
			r.byDay = map[time.Weekday]bool{}
			for _, code := range strings.Split(val, ",") {
				if wd, ok := weekdayCodes[strings.ToUpper(strings.TrimSpace(code))]; ok {
					r.byDay[wd] = true
				}
			}
		case "UNTIL":
			if t, err := time.Parse(time.RFC3339, val); err == nil {
				r.until = t
				r.hasUntil = true
			}
		case "COUNT":
			if n, err := strconv.Atoi(val); err == nil && n > 0 {
				r.count = n
			}
		}
	}
	switch r.freq {
	case "DAILY", "WEEKLY", "MONTHLY", "YEARLY", "WEEKDAY":
		return r, true
	default:
		return recRule{}, false
	}
}

// expandEvent turns a stored master event into the concrete instances that
// overlap [min, max). A non-recurring event is returned unchanged (as a single
// instance) when it overlaps the window. Recurring instances carry the master
// id in RecurringEventID and have their StartAt/EndAt shifted per occurrence.
func expandEvent(master Event, min, max time.Time) []Event {
	rule, ok := parseRecurrence(master.Recurrence)
	if !ok {
		// Non-recurring: include only if it overlaps the window.
		if master.StartAt.Before(max) && master.EndAt.After(min) {
			return []Event{master}
		}
		return nil
	}

	dur := master.EndAt.Sub(master.StartAt)
	if dur < 0 {
		dur = 0
	}

	var out []Event
	emit := func(start time.Time) {
		end := start.Add(dur)
		if start.Before(max) && end.After(min) {
			inst := master
			inst.StartAt = start
			inst.EndAt = end
			inst.RecurringEventID = master.ID
			out = append(out, inst)
		}
	}

	emitted := 0 // occurrences generated by the rule (for COUNT)
	withinCount := func() bool { return rule.count == 0 || emitted < rule.count }

	switch rule.freq {
	case "DAILY":
		for cur := master.StartAt; cur.Before(max) && withinCount(); cur = cur.AddDate(0, 0, rule.interval) {
			if rule.hasUntil && cur.After(rule.until) {
				break
			}
			emit(cur)
			emitted++
			if len(out) >= maxOccurrences {
				break
			}
		}

	case "WEEKDAY":
		// Every Mon–Fri (interval ignored, matches Google's "Every weekday").
		for cur := master.StartAt; cur.Before(max) && withinCount(); cur = cur.AddDate(0, 0, 1) {
			if rule.hasUntil && cur.After(rule.until) {
				break
			}
			if wd := cur.Weekday(); wd == time.Saturday || wd == time.Sunday {
				continue
			}
			emit(cur)
			emitted++
			if len(out) >= maxOccurrences {
				break
			}
		}

	case "WEEKLY":
		// Determine which weekdays fire. Default: the master's own weekday.
		days := rule.byDay
		if len(days) == 0 {
			days = map[time.Weekday]bool{master.StartAt.Weekday(): true}
		}
		// Walk week by week from the master's week start (Sunday), honouring
		// INTERVAL, and emit each selected weekday at the master's clock time.
		weekStart := startOfWeekAt(master.StartAt)
		for wk := weekStart; wk.Before(max) && withinCount(); wk = wk.AddDate(0, 0, 7*rule.interval) {
			for offset := 0; offset < 7; offset++ {
				cur := setClock(wk.AddDate(0, 0, offset), master.StartAt)
				if cur.Before(master.StartAt) {
					continue // don't emit occurrences before the series start
				}
				if !days[cur.Weekday()] {
					continue
				}
				if rule.hasUntil && cur.After(rule.until) {
					return sortInstances(out)
				}
				if !withinCount() {
					return sortInstances(out)
				}
				emit(cur)
				emitted++
				if len(out) >= maxOccurrences {
					return sortInstances(out)
				}
			}
		}

	case "MONTHLY":
		for cur := master.StartAt; cur.Before(max) && withinCount(); cur = addMonthsClamped(cur, rule.interval) {
			if rule.hasUntil && cur.After(rule.until) {
				break
			}
			emit(cur)
			emitted++
			if len(out) >= maxOccurrences {
				break
			}
		}

	case "YEARLY":
		for cur := master.StartAt; cur.Before(max) && withinCount(); cur = cur.AddDate(rule.interval, 0, 0) {
			if rule.hasUntil && cur.After(rule.until) {
				break
			}
			emit(cur)
			emitted++
			if len(out) >= maxOccurrences {
				break
			}
		}
	}

	return sortInstances(out)
}

func sortInstances(out []Event) []Event {
	sort.Slice(out, func(i, j int) bool { return out[i].StartAt.Before(out[j].StartAt) })
	return out
}

// startOfWeekAt returns the Sunday 00:00 (in the time's own location) of the
// week containing t.
func startOfWeekAt(t time.Time) time.Time {
	d := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, t.Location())
	return d.AddDate(0, 0, -int(d.Weekday()))
}

// setClock returns day's calendar date with ref's clock time (hour/min/sec).
func setClock(day, ref time.Time) time.Time {
	return time.Date(day.Year(), day.Month(), day.Day(),
		ref.Hour(), ref.Minute(), ref.Second(), ref.Nanosecond(), ref.Location())
}

// addMonthsClamped advances by n months. Go's AddDate would roll Jan 31 → Mar 3
// when the target month is shorter; clamp to the last day of the target month
// instead so a "31st of the month" series lands on Feb 28, Apr 30, etc.
func addMonthsClamped(t time.Time, n int) time.Time {
	y, m, d := t.Year(), int(t.Month())+n, t.Day()
	// normalise month into [1,12] with year carry
	y += (m - 1) / 12
	m = (m-1)%12 + 1
	if m <= 0 {
		m += 12
		y--
	}
	last := daysInMonth(y, time.Month(m))
	if d > last {
		d = last
	}
	return time.Date(y, time.Month(m), d, t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), t.Location())
}

func daysInMonth(year int, m time.Month) int {
	return time.Date(year, m+1, 0, 0, 0, 0, 0, time.UTC).Day()
}
