// Table of contents and table of figures (Docs M8).
//
// A `tableOfContents` block holds `tocEntry` paragraphs and the TOC field
// instruction it was built from (`TOC \o "1-3" \h \z \u`; a table of
// figures is `TOC \h \z \c "Figure"`). Entries are regenerated by
// `rebuildTocs` (F9 / Update table): headings and paragraphs with an
// outline level in the \o range, or captions whose SEQ field has the \c
// label. Each source paragraph gets a hidden `_Toc<n>` bookmark; with \h
// an entry's text links to it. Page numbers come from the page resolver
// (explicit breaks until M9) and sit right-aligned after a tab leader.
import { Node, mergeAttributes, type Editor } from "@tiptap/core";
import type { Node as PMNode } from "@tiptap/pm/model";
import type { Transaction } from "@tiptap/pm/state";
import { ensureBookmark } from "./bookmarks";
import { outlineLevelOf, parseInstr, textWithFields, type FieldEnv } from "./fields";
import type { StyleSheet } from "./styles";

export const TOC_DEFAULT = 'TOC \\o "1-3" \\h \\z \\u';
export const tofInstr = (label: string) => `TOC \\h \\z \\c "${label.replace(/"/g, "")}"`;

export type TocLeader = "dot" | "dash" | "underline" | "none";

export interface TocOptions {
  /** Outline levels shown (\o "a-b"). */
  from: number;
  to: number;
  hyperlinks: boolean;
  pageNumbers: boolean;
  /** Table of figures: the caption label (\c). */
  caption: string | null;
}

export function tocOptions(instr: string): TocOptions {
  const p = parseInstr(instr);
  const o = typeof p.sw.o === "string" ? /^(\d)\s*-\s*(\d)$/.exec(p.sw.o) : null;
  return {
    from: o ? +o[1] : 1,
    to: o ? +o[2] : p.sw.o || p.sw.u ? 9 : 3,
    hyperlinks: !!p.sw.h,
    pageNumbers: !p.sw.n,
    caption: typeof p.sw.c === "string" ? p.sw.c : null,
  };
}

export function tocInstr(o: TocOptions): string {
  if (o.caption) return `TOC ${o.hyperlinks ? "\\h " : ""}\\z ${o.pageNumbers ? "" : "\\n "}\\c "${o.caption.replace(/"/g, "")}"`.replace(/\s+/g, " ").trim();
  return `TOC \\o "${o.from}-${o.to}" ${o.hyperlinks ? "\\h " : ""}\\z ${o.pageNumbers ? "" : "\\n "}\\u`.replace(/\s+/g, " ").trim();
}

// --- nodes ------------------------------------------------------------------------------

type UpdateHandler = (editor: Editor, pos: number) => void;
let updateHandler: UpdateHandler | null = null;
/** references.ts installs the Update button's action (avoids an import cycle). */
export function setTocUpdateHandler(fn: UpdateHandler) {
  updateHandler = fn;
}

export const TableOfContents = Node.create({
  name: "tableOfContents",
  group: "block",
  content: "tocEntry+",
  defining: true,
  isolating: true,
  addAttributes() {
    return {
      instr: {
        default: TOC_DEFAULT,
        parseHTML: (el) => (el as HTMLElement).getAttribute("data-toc") || TOC_DEFAULT,
        renderHTML: (a) => ({ "data-toc": a.instr }),
      },
      leader: {
        default: "dot",
        parseHTML: (el) => (el as HTMLElement).getAttribute("data-leader") || "dot",
        renderHTML: (a) => ({ "data-leader": a.leader }),
      },
    };
  },
  parseHTML() {
    return [{ tag: "div[data-toc]" }];
  },
  renderHTML({ node, HTMLAttributes }) {
    const o = tocOptions(String(node.attrs.instr ?? ""));
    return [
      "div",
      mergeAttributes(HTMLAttributes, {
        class: "doc-toc",
        "data-kind": o.caption ? "figures" : "contents",
        ...(o.pageNumbers ? {} : { "data-no-pages": "true" }),
      }),
      0,
    ];
  },
  addNodeView() {
    return ({ node, editor, getPos, HTMLAttributes }) => {
      const dom = document.createElement("div");
      const setAttrs = (n: PMNode) => {
        const o = tocOptions(String(n.attrs.instr ?? ""));
        dom.className = "doc-toc";
        dom.setAttribute("data-toc", String(n.attrs.instr));
        dom.setAttribute("data-leader", String(n.attrs.leader ?? "dot"));
        dom.setAttribute("data-kind", o.caption ? "figures" : "contents");
        dom.setAttribute("data-testid", "doc-toc");
        if (o.pageNumbers) dom.removeAttribute("data-no-pages");
        else dom.setAttribute("data-no-pages", "true");
      };
      void HTMLAttributes;
      setAttrs(node);
      const bar = document.createElement("div");
      bar.className = "doc-toc-bar";
      bar.contentEditable = "false";
      const btn = document.createElement("button");
      btn.type = "button";
      btn.textContent = "Update table";
      btn.setAttribute("data-testid", "toc-update");
      btn.addEventListener("mousedown", (e) => e.preventDefault());
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        const pos = typeof getPos === "function" ? getPos() : null;
        if (pos != null && editor.isEditable) updateHandler?.(editor, pos);
      });
      bar.appendChild(btn);
      const content = document.createElement("div");
      content.className = "doc-toc-content";
      dom.append(bar, content);
      return {
        dom,
        contentDOM: content,
        update: (n: PMNode) => {
          if (n.type.name !== "tableOfContents") return false;
          setAttrs(n);
          return true;
        },
        ignoreMutation: (m) => bar.contains(m.target as globalThis.Node) || (m.type === "attributes" && m.target === dom),
      };
    };
  },
});

export const TocEntry = Node.create({
  name: "tocEntry",
  content: "inline*",
  defining: true,
  addAttributes() {
    return {
      level: {
        default: 1,
        parseHTML: (el) => Math.min(9, Math.max(1, parseInt((el as HTMLElement).getAttribute("data-level") ?? "1", 10) || 1)),
        renderHTML: (a) => ({ "data-level": String(a.level) }),
      },
      page: {
        default: "",
        parseHTML: (el) => (el as HTMLElement).getAttribute("data-page") ?? "",
        renderHTML: (a) => ({ "data-page": String(a.page ?? "") }),
      },
    };
  },
  parseHTML() {
    return [{ tag: "p.doc-toc-entry", contentElement: ".toc-text", priority: 60 }];
  },
  renderHTML({ node, HTMLAttributes }) {
    return [
      "p",
      mergeAttributes(HTMLAttributes, { class: "doc-toc-entry" }),
      ["span", { class: "toc-text" }, 0],
      ["span", { class: "toc-leader", contenteditable: "false" }],
      ["span", { class: "toc-page", contenteditable: "false" }, String(node.attrs.page ?? "")],
    ];
  },
});

// --- building ---------------------------------------------------------------------------

export interface TocItem {
  pos: number;
  level: number;
  text: string;
  /** Content range of the source paragraph. */
  from: number;
  to: number;
}

/** Does paragraph `node` contain a SEQ field for `label`? */
export function hasSeq(node: PMNode, label: string): boolean {
  let hit = false;
  node.descendants((n) => {
    if (hit) return false;
    if (n.type.name === "field") {
      const p = parseInstr(String(n.attrs.instr ?? ""));
      if (p.type === "SEQ" && (p.args[0] ?? "").toLowerCase() === label.toLowerCase()) hit = true;
    }
    return !hit;
  });
  return hit;
}

/** tocItems lists the paragraphs a TOC with `instr` shows, in order. */
export function tocItems(doc: PMNode, instr: string, sheet?: StyleSheet | null, results?: Map<number, string>): TocItem[] {
  const o = tocOptions(instr);
  const out: TocItem[] = [];
  doc.descendants((n, pos) => {
    if (n.type.name === "tableOfContents") return false;
    if (!n.isTextblock) return true;
    if (n.type.name !== "paragraph" && n.type.name !== "heading") return false;
    const from = pos + 1;
    const to = pos + n.nodeSize - 1;
    const text = textWithFields(doc, from, to, results).replace(/\s+/g, " ").trim();
    if (!text) return false;
    if (o.caption) {
      if (hasSeq(n, o.caption)) out.push({ pos, level: 1, text, from, to });
      return false;
    }
    const level = outlineLevelOf(n, sheet);
    if (level && level >= o.from && level <= o.to) out.push({ pos, level, text, from, to });
    return false;
  });
  return out;
}

/** tableOfContentsNodes lists the TOC nodes (position, node). */
export function tocNodes(doc: PMNode): { pos: number; node: PMNode }[] {
  const out: { pos: number; node: PMNode }[] = [];
  doc.descendants((n, pos) => {
    if (n.type.name === "tableOfContents") {
      out.push({ pos, node: n });
      return false;
    }
    return !n.isTextblock;
  });
  return out;
}

/**
 * rebuildTocs regenerates the entries of the TOC nodes at `only` (all when
 * omitted) in `tr`, adding `_Toc` bookmarks to their source paragraphs.
 * `results` are fresh field results to use in entry text. Returns the
 * number of tables rebuilt.
 */
export function rebuildTocs(tr: Transaction, env: FieldEnv, only?: Set<number>, results?: Map<number, string>): number {
  const tocs = tocNodes(tr.doc).filter((t) => !only || only.has(t.pos));
  if (!tocs.length) return 0;
  const schema = tr.doc.type.schema;
  // Bookmarks first: marks don't move positions.
  const plans = tocs.map((t) => {
    const instr = String(t.node.attrs.instr ?? TOC_DEFAULT);
    const o = tocOptions(instr);
    const items = tocItems(tr.doc, instr, env.sheet, results).map((it) => ({
      ...it,
      name: ensureBookmark(tr, it.from, it.to, "_Toc", true),
      page: o.pageNumbers ? String(env.pages.pageAt(it.pos)) : "",
    }));
    return { ...t, o, items };
  });
  for (const plan of plans.sort((a, b) => b.pos - a.pos)) {
    const node = tr.doc.nodeAt(plan.pos);
    if (!node || node.type.name !== "tableOfContents") continue;
    const entries = plan.items.length
      ? plan.items.map((it) =>
          schema.nodes.tocEntry.create(
            { level: it.level, page: it.page },
            schema.text(it.text, plan.o.hyperlinks ? [schema.marks.link.create({ href: `#${it.name}` })] : []),
          ),
        )
      : [
          schema.nodes.tocEntry.create(
            { level: 1, page: "" },
            schema.text(plan.o.caption ? "No table of figures entries found." : "No table of contents entries found."),
          ),
        ];
    tr.replaceWith(plan.pos + 1, plan.pos + node.nodeSize - 1, entries);
  }
  return plans.length;
}

// --- Add text (outline level for the TOC) ---------------------------------------------

/**
 * setTocLevel implements References ▸ Add text: level 1-9 puts the
 * selected paragraphs in the table of contents at that level (as an
 * outline level; a heading of that level just drops any override); 0
 * ("Do not show in table of contents") gives body-text level, which for a
 * heading is the explicit outline level 10.
 */
export function setTocLevel(editor: Editor, level: number, sheet?: StyleSheet | null): boolean {
  const { state } = editor;
  const tr = state.tr;
  const { from, to } = state.selection;
  state.doc.nodesBetween(from, to, (n, pos) => {
    if (n.type.name !== "paragraph" && n.type.name !== "heading") return !n.isTextblock;
    const styleLevel = outlineLevelOf(n.type.create({ ...n.attrs, outlineLevel: null }), sheet);
    let next: number | null;
    if (level <= 0) next = styleLevel ? 10 : null;
    else next = styleLevel === level ? null : level;
    if ((n.attrs.outlineLevel ?? null) !== next) tr.setNodeMarkup(pos, undefined, { ...n.attrs, outlineLevel: next });
    return false;
  });
  if (!tr.docChanged) return false;
  editor.view.dispatch(tr);
  return true;
}

/** tocLevelAtSelection: the Add text level of the caret's paragraph. */
export function tocLevelAtSelection(editor: Editor, sheet?: StyleSheet | null): number {
  const n = editor.state.selection.$from.parent;
  return outlineLevelOf(n, sheet) ?? 0;
}
